[package]
name = "psd-sprite"
version = "0.1.0"
edition = "2021"

[dependencies]
psd = { path = "../third-party-forks/psd" }
namui-type = { path = "../../namui/namui-type" }
rayon = "1.10.0"
anyhow = { version = "1.0.86", features = ["backtrace"] }
skia-safe = { path = "../../namui/third-party-forks/rust-skia/skia-safe" }
tokio = { path = "../../namui/third-party-forks/tokio/tokio", features = [
    "rt",
] }
schema-0 = { version = "0.0.1", path = "../new-server/database/schema/0" }
nimg = { path = "../nimg" }
serde = { version = "1.0.209", features = ["derive"] }
bincode = "1.3.3"
futures-core = "0.3.30"
zstd = "0.13.2"
bytes = "1.7.1"
futures-util = { version = "0.3.30", features = ["io"] }
async-compression = { version = "0.4.12", features = ["futures-io", "zstd"] }

[profile.dev.package.nimg]
opt-level = 3
