[package]
name = "namui-skia"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[features]
default = []
windows = ["skia-safe/d3d", "dep:windows"]
wasm = [
    "dep:canvas-kit-wasm-bindgen",
    "dep:wasm-bindgen",
    "dep:web-sys",
    "dep:js-sys",
    "dep:wasm-bindgen-futures",
]


[dependencies]
windows = { version = "0.52.0", features = [
    "Win32",
    "Win32_Graphics",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Foundation",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System",
], optional = true }
anyhow = { version = "1.0.75", features = ["backtrace"] }
namui-type = { path = "../../namui-type", features = ["skia"] }
serde = { version = "1.0.183", features = ["derive"] }
skia-safe = { path = "../rust-skia/skia-safe", optional = true }
canvas-kit-wasm-bindgen = { path = "../canvas-kit-wasm-bindgen", optional = true }
js-sys = { version = "0.3.64", optional = true }
wasm-bindgen = { version = "0.2.87", optional = true }
web-sys = { version = "0.3.64", features = [
    "ImageBitmap",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "Blob",
], optional = true }
wasm-bindgen-futures = { version = "0.4.37", optional = true }
woff2 = "0.3.0"

[dev-dependencies]

[target.'cfg(target_family="wasm")'.dev-dependencies]
wasm-bindgen-test = "0.2"
