[package]
name = "namui-skia"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc"]

[features]
default = []
windows = ["skia-safe/d3d", "dep:windows"]
skia = ["skia-safe", "namui-type/skia"]
wasm-runtime = []
wasm-drawer = []

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
namui-type = { path = "../../namui-type" }
derive-macro = { path = "../../namui-type/derive-macro" }
woff2 = { path = "../woff2-rs" }
serde = { version = "1.0", features = ["derive", "rc"] }
num = { version = "0.4.0", features = ["std"] }
ordered-float = { version = "4.2.0", features = ["serde"] }
uuid = { version = "1.1", features = [
    "v4",
    "js",
    "macro-diagnostics",
    "serde",
] }
url = { version = "2.4.0", features = ["serde"] }
postcard = { version = "1.0.6", features = ["use-std"] }
textwrap = "0.16.0"
unicode-segmentation = "1.10.1"
winit = { version = "0.29.4", optional = true }
derivative = "2.2.0"
dashmap = "5.5.3"
float-cmp = "0.9.0"

[target.'cfg(not(target_family="wasm"))'.dependencies]
skia-safe = { version = "0.73.0", optional = true }
windows = { version = "0.56.0", features = [
    "Win32",
    "Win32_Graphics",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Foundation",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System",
], optional = true }


[target.'cfg(target_family="wasm")'.dependencies]
wasm-bindgen = "0.2.87"
canvas-kit-wasm-bindgen = { path = "../canvas-kit-wasm-bindgen" }
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"
web-sys = { version = "0.3.64", features = ["ImageBitmap"] }


[target.'cfg(target_family="wasm")'.dev-dependencies]
wasm-bindgen-test = "0.2"
