[package]
name = "hooks-v2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tokio = { version = "1", default-features = false, features = ["sync", "rt"] }
namui = { path = "../.." }
namui-prebuilt = { path = "../../../namui-prebuilt" }
crossbeam = "0.8.2"
