[package]
edition = "2021"
name = "export-known-ids-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
regex = "1.6.0"
lazy_static = "1.4.0"
syn = { version = "1.0", features =  ["derive"] }
quote = "1.0"
