[package]
name = "schema-0"
version = "0.0.1"
edition = "2021"

[dependencies]
document = { path = "../document" }
schema-macro = { path = "../macro" }
rkyv = { version = "0.8.8" }
namui-type = { path = "../../../../../namui/namui-type" }
