[package]
name = "oioi-agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
aws-config = "1.5.4"
aws-sdk-ssm = "1.3.0"
bollard = "0.15.0"
chrono = { version = "0.4.31", features = ["serde"] }
futures-util = "0.3.29"
lazy_static = "1.4.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["full"] }
