#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
pub use luda_rpc::project::get_projects::*;
pub type OptionResult = Option<Result<Response, Error>>;
pub fn get_projects<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest<'a>>,
    dependencies: Deps,
) -> Sig<'a, OptionResult, &'a OptionResult> {
    server_rpc(ctx, request, dependencies, 2u16)
}
pub fn get_projects_render<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest<'a>>,
    dependencies: Deps,
    on_loading: impl FnOnce(),
    on_err: impl FnOnce(&Error),
    on_res: impl FnOnce(&Response),
) {
    match get_projects(ctx, request, dependencies).as_ref() {
        Some(result) => match result {
            Ok(res) => on_res(res),
            Err(err) => on_err(err),
        },
        None => on_loading(),
    }
}
