[package]
name = "namui-particle"
version = "0.1.0"
edition = "2021"

[dependencies]
namui-type = { path = "../namui-type" }
namui-hooks = { path = "../namui-hooks" }
namui-skia = { path = "../skia" }
tokio = { path = "../third-party-forks/tokio/tokio", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
    "rt-multi-thread",
    "fs",
] }