mod character_should_escape_edge_of_wall;
mod character_should_not_move_on_cross_axis_when_collide;

pub use character_should_escape_edge_of_wall::*;
pub use character_should_not_move_on_cross_axis_when_collide::*;
