#![allow(unused_doc_comments, dead_code)]

mod canvas;
mod canvas_kit;
mod color_filter_factory;
mod embind_object;
mod enums;
mod font;
mod font_mgr;
mod font_mgr_factory;
mod image;
mod matrix_3x3_helpers;
mod paint;
mod path;
mod runtime_effect;
mod runtime_effect_factory;
mod shader;
mod surface;
mod text_blob;
mod text_blob_factory;
mod typeface;

pub(crate) use canvas::*;
pub(crate) use canvas_kit::*;
pub(crate) use color_filter_factory::*;
pub(crate) use enums::*;
pub(crate) use font::*;
pub(crate) use font_mgr::*;
pub(crate) use font_mgr_factory::*;
pub(crate) use image::*;
pub(crate) use matrix_3x3_helpers::*;
pub(crate) use paint::*;
pub(crate) use path::*;
pub(crate) use runtime_effect::*;
pub(crate) use runtime_effect_factory::*;
pub(crate) use shader::*;
pub(crate) use surface::*;
pub(crate) use text_blob::*;
pub(crate) use text_blob_factory::*;
pub(crate) use typeface::*;
use wasm_bindgen::prelude::*;
