name: Init test job
runs:
  using: composite
  steps:
    - name: rust update & cargo version env set
      shell: bash
      run: |
        rustup update
        CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/
          namui-cli/target/
        key: ${{ runner.os }}-${{ env.CARGO_VERSION }}-init-test-${{ hashFiles('namui-cli/Cargo.lock') }}

    - name: wasm-pack install
      shell: bash
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - shell: bash
      run: rustup target add wasm32-unknown-unknown

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install namui-cli
      shell: bash
      run: bash namui-cli/scripts/install.sh
