name: Init test job
runs:
  using: composite
  steps:
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: init-test-job

    - name: update rust stable
      shell: bash
      run: rustup update

    - name: wasm-pack install
      shell: bash
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f

    - shell: bash
      run: rustup target add wasm32-unknown-unknown

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: namui-cli
        cache-directories: namui-cli

    - name: install namui-cli
      shell: bash
      run: bash namui-cli/scripts/install.sh
