// Auto-generated by forte build

export const paths = {
  "/oauth/cli/authorize": () => "/oauth/cli/authorize",
  "/oauth/github/callback": () => "/oauth/github/callback",
  "/builds": () => "/builds",
  "/": () => "/",
  "/issues/:hash": ({hash}: {hash: string}) => `/issues/${hash}`,
  "/tokens": () => "/tokens",
  "/login": () => "/login",
} as const;
