#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
use ::rpc::team::get_teams::*;
pub type OptionResult = Option<Result<Response, Error>>;
pub trait RequestOptional: Into<Option<Request>> {}
impl RequestOptional for Request {}
impl RequestOptional for Option<Request> {}
pub fn get_teams<'a, Req: RequestOptional, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Req,
    dependencies: Deps,
) -> Sig<'a, OptionResult, &'a OptionResult> {
    server_rpc(ctx, |deps| request(deps).into(), dependencies)
}
