use crate::*;
use build_helper::write_fmt;
use quote::quote;

pub fn generate_code(rpc: &Rpc) {
    generate_rpc_files(rpc);
}

fn client_src_path() -> &'static std::path::Path {
    std::path::Path::new("../../new-client/src")
}

fn generate_rpc_files(rpc: &Rpc) {
    let rpc_path = client_src_path().join("rpc");
    let mut rpc_mod_rs_lines = rpc
        .services
        .iter()
        .map(|service| format!("pub mod {};\n", service.snake_case_name,))
        .collect::<Vec<String>>();
    rpc_mod_rs_lines.sort();
    std::fs::write(
        rpc_path.join("mod.rs"),
        "//! This is Generated by rpc build.rs\n\n".to_string() + &rpc_mod_rs_lines.join(""),
    )
    .unwrap();

    let mut api_index: u16 = 0;

    for service in &rpc.services {
        let service_snake_name = &service.snake_case_name;
        let service_path = rpc_path.join(service_snake_name.to_string());
        if !service_path.exists() {
            std::fs::create_dir_all(&service_path).unwrap();
        }

        let mut service_mod_rs_lines = service
            .apis
            .iter()
            .map(|api| format!("pub mod {};\n", api.name))
            .collect::<Vec<String>>();
        service_mod_rs_lines.sort();
        std::fs::write(
            service_path.join("mod.rs"),
            "//! This is Generated by rpc build.rs\n\n".to_string()
                + &service_mod_rs_lines.join(""),
        )
        .unwrap();

        for api in &service.apis {
            let api_dir = service_path.join(format!("{}", api.name));
            std::fs::create_dir_all(&api_dir).unwrap();
            let api_mod_rs = api_dir.join("mod.rs");
            let api_name = &api.name;
            let api_name_render = syn::Ident::new(&format!("{api_name}_render"), api.name.span());

            let ref_request_implicit_lifetime = match &api.request {
                syn::Item::Enum(_item_enum) => {
                    todo!()
                }
                syn::Item::Struct(item_struct) => {
                    if item_struct.fields.is_empty() {
                        quote! { RefRequest }
                    } else {
                        quote! { RefRequest<'a> }
                    }
                }
                _ => panic!("Request must be a struct or enum"),
            };

            let content = quote! {
                //! This is Generated by rpc build.rs
                use crate::{*, network::*};
                pub use luda_rpc::#service_snake_name::#api_name::*;

                pub type OptionResult = Option<Result<Response, Error>>;

                pub fn #api_name<'a, Deps: Dependencies + 'a>(
                    ctx: &'a RenderCtx,
                    request: impl FnOnce(Deps) -> Option<#ref_request_implicit_lifetime>,
                    dependencies: Deps,
                ) -> Sig<'a, OptionResult, &'a OptionResult> {
                    server_rpc(ctx, request, dependencies, #api_index)
                }

                pub fn #api_name_render<'a, Deps: Dependencies + 'a>(
                    ctx: &'a RenderCtx,
                    request: impl FnOnce(Deps) -> Option<#ref_request_implicit_lifetime>,
                    dependencies: Deps,
                    on_loading: impl FnOnce(),
                    on_err: impl FnOnce(&Error),
                    on_res: impl FnOnce(&Response),
                ) {
                    match #api_name(ctx, request, dependencies).as_ref() {
                        Some(result) => match result {
                            Ok(res) => on_res(res),
                            Err(err) => on_err(err),
                        },
                        None => on_loading(),
                    }
                }
            };
            write_fmt(api_mod_rs, content);

            api_index += 1;
        }
    }
}
