[package]
name = "quick"
version = "0.1.0"
edition = "2021"

[dependencies]
namui = { path = "../namui" }
namui-prebuilt = { path = "../namui-prebuilt" }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"