[package]
name = "register-font"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[dependencies]
namui = { path = "../../namui" }

[dev-dependencies]
wasm-bindgen-test = "0.3"
