[package]
name = "audio"
version = "0.1.0"
edition = "2021"
namui = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
namui = { path = "../.." }
namui-prebuilt = { path = "../../../namui-prebuilt" }

[dev-dependencies]
wasm-bindgen-test = "0.3"
