name: Push docker image
runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push namui-test-host image
      shell: bash
      run: time podman push $LATEST_IMAGE_NAME
