name: Push docker image
runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push namui-test-host image
      shell: bash
      run: docker push $IMAGE_NAME
