//! This is Generated by rpc build.rs

mod common;
pub mod create_team_invite_code;
pub mod invalidate_team_invite_code;
pub mod join_team;
pub mod list_team_invite_codes;

#[allow(unused_imports)]
pub use common::*;
