[package]
name = "vvv"
version = "0.1.0"
edition = "2021"

[features]
vec = []

[dependencies]
anyhow = { version = "1.0.91", features = ["backtrace"] }
bytes = "1.8.0"

[dev-dependencies]
criterion = { version = "0.5" }

[[bench]]
name = "benchmark"
harness = false
required-features = ["vec"]
