[package]
name = "image-load-background"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
