[package]
name = "image-load-background"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
namui = { path = "../.." }
namui-prebuilt = { path = "../../../namui-prebuilt" }

[dev-dependencies]
wasm-bindgen-test = "0.3"
