[package]
name = "namui-light"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2024"

[package.metadata.namui]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "wasm32-wasi-web",
    "aarch64-apple-darwin",
]

[dependencies]
namui-type = { path = "../namui-type" }
namui-hooks = { path = "../namui-hooks" }
namui-skia = { path = "../skia" }
namui-cfg = { path = "../namui-cfg" }
namui-particle = { path = "../particle" }
lazy_static = "1.4.0"
anyhow = { version = "1.0.77", features = ["backtrace"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
percent-encoding = "2"
futures = "0.3.17"
num = { version = "0.4.0", features = ["std"] }
dashmap = "5"
rand = "0.8.5"
tokio = { path = "../third-party-forks/tokio/tokio", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
    "rt-multi-thread",
    "fs",
] }
tokio-stream = { path = "../third-party-forks/tokio/tokio-stream" }
rayon = { path = "../third-party-forks/rayon" }
http = "1.1.0"
http-body = "1.0.1"
bytes = "1.7.1"
hyper = "1.4.1"
http-body-util = "0.1.2"
pin-project = "1"

[dev-dependencies]
float-cmp = "0.9"
