[package]
name = "namui-audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
namui-type = { path = "../namui-type" }
anyhow = "1.0.72"
tokio = { version = "1", default-features = false, features = ["full"] }
cpal = "0.15.2"
# opus = "0.3.0"
symphonia = "0.5.3"
