[package]
name = "canvas-kit-wasm-bindgen"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2" }
js-sys = "0.3.55"
namui-type = { path = "../../namui-type" }
lazy_static = "1.4.0"
once_cell = "1.18.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlCanvasElement",
]
