[package]
name = "revert-json-patch"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.99", features = ["derive"] }
serde_json = "1.0.40"
treediff = { version = "3.0.1", features = ["with-serde-json"] }

[dev-dependencies]
rand = "0.5.0"
serde_json = { version = "1.0.40", features = ["preserve_order"] }
