name: 'Check Formatting'
on: [push, pull_request]

jobs:
  check-fmt:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Rust
      run: |
        rustup update stable
        rustup default stable 
        rustup component add rustfmt
    - name: Generate missing bindings.rs file
      run: |
        echo > skia-bindings/src/bindings.rs
    - run: | 
        cargo fmt -- --check
