# Supplemental workflow for testing alternative build configurations.

name: 'supplemental-builds'
on:
  push:
    branches-ignore:
      - release
  pull_request:
    branches-ignore:
      - release
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: 'supplemental-builds-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  linux-local-build:
    runs-on: ubuntu-20.04
    container: ghcr.io/pragmatrix/rust-skia-linux:latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Fix git dubious ownership errors when synchronizing Skia dependencies
      run: git config --global --add safe.directory '*'

    - name: Prepare Rustup
      run: (cd /github/home && ln -s /root/.cargo)

    - name: Update Rustup and Rust
      run: rustup update

    - name: Configure Rust Toolchain
      run: rustup default stable

    - name: 'Test local builds (#527)'
      shell: bash
      run: |
        make test-local-build

  linux-wasm:
    runs-on: ubuntu-20.04
    container: ghcr.io/pragmatrix/rust-skia-linux:latest
    env:
      EMCC_CFLAGS: "-s ERROR_ON_UNDEFINED_SYMBOLS=0 -s MAX_WEBGL_VERSION=2"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Fix git dubious ownership errors when synchronizing Skia dependencies
      run: git config --global --add safe.directory '*'

    - name: Prepare Rustup
      run: (cd /github/home && ln -s /root/.cargo)

    - name: Update Rustup and Rust
      run: rustup update

    - name: Configure Rust Toolchain
      run: rustup default stable

    - name: Install wasm32-unknown-emscripten Target
      run: rustup target add wasm32-unknown-emscripten

    - name: 'Build with Target wasm32-unknown-emscripten'
      shell: bash
      run: |
        source /emsdk/emsdk_env.sh && cd wasm-example && cargo build --target wasm32-unknown-emscripten

  # https://github.com/rust-skia/rust-skia/issues/535
  # linux-arm64-build:
  #   runs-on: ubuntu-20.04
  #   container: ghcr.io/pragmatrix/rust-skia-linux-arm64:latest

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: true

  #   - name: 'Build arm64 (#535)'
  #     shell: bash
  #     run: |
  #       cargo build -vv --features "gl"

  windows-link-dead-code-gpu-textlayout:
    runs-on: windows-2022

    steps:
    - name: Attempt to fix git dubious ownership warnings
      run: git config --global --add safe.directory '*'

    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1.4.0
      with:
        rust-version: stable

    - name: Python Version
      run: python --version

    - name: Upgrade LLVM
      run: choco upgrade llvm

    - name: 'Build with RUSTFLAGS=-Clink-dead-code (#318)'
      run: |
        # See https://github.com/rust-lang/rust/issues/90056 why we have to provide a target.
        # proc-macro-error 1.0.4 causes a no metadata found: failed to decompress metadata error.
        cargo build --features gl,vulkan,d3d,textlayout,webp --target x86_64-pc-windows-msvc
      env:
        RUSTFLAGS: '-Clink-dead-code'

  windows-link-dead-code:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: hecrj/setup-rust-action@master
      with:
        rust-version: stable

    - name: Python Version
      run: python --version

    - name: Upgrade LLVM
      run: choco upgrade llvm

    - name: 'Build with RUSTFLAGS=-Clink-dead-code (#318)'
      run: |
        # See https://github.com/rust-lang/rust/issues/90056 why we have to provide a target.
        # proc-macro-error 1.0.4 causes a no metadata found: failed to decompress metadata error.
        cargo build --target x86_64-pc-windows-msvc
      env:
        RUSTFLAGS: '-Clink-dead-code'

  windows-x86:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install Rust
      uses: hecrj/setup-rust-action@v1.4.0
      with:
        rust-version: nightly

    - name: Python Version
      run: python --version

    - name: Upgrade LLVM
      run: choco upgrade llvm

    - name: 'Install Rust target i686-pc-windows-msvc'
      shell: bash
      run: |
        rustup target add i686-pc-windows-msvc

    - name: 'Build target i686-pc-windows-msvc (#540)'
      run: |
        cargo build --features gl,vulkan,d3d,textlayout,webp --target i686-pc-windows-msvc
