[package]
edition = "2021"
name = "rpc-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.29"
syn = { version = "2.0.22", features = ["full"] }
rpc-parser = { path = "../rpc-parser" }
