[package]
edition = "2021"
name = "rpc-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6.0"
proc-macro2 = "1.0.63"
quote = "1.0.29"
syn = { version = "2.0.22", features = ["full"] }
