[package]
name = "server-dev-cli"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
server-core = { path = "../server-core" }
clap = { version = "4.1.4", features = ["derive"] }
tokio = "1.21"
