name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected...
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: I actually...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: 1. Go to '...'
  - type: textarea
    id: other-info
    attributes:
      label: Other Info
      description: Any other information about the problem.
      placeholder: Other info...
