name: Luda Image(CG) Request
description: Reqeust new image for luda
title: "[Luda Character CG]: "
labels: ["luda image request"]
assignees:
  - takiki2828
body:
  - type: textarea
    id: context
    attributes:
      label: 시퀀스 & 컷 리스트
      description: 어느 컷에서 사용할 것인지 전반적인 흐름을 알 수 있도록, 컷 리스트에서 다른 컷도 보이는 상태에서 해당 컷을 강조하여 올려주세요.
    validations:
      required: true
  - type: input
    id: cut-preview-url
    attributes:
      label: 컷 미리보기 주소
      description: 어느 장면에서 사용할 이미지인지 Preview Url을 입력해주세요.
      placeholder: 예) https://s3.ap-northeast-2.amazonaws.com/luda-editor/master/www/index.html?view&sequence_id=9b536870-45b5-4ed4-8af6-604c9b113ae4
    validations:
      required: false
  - type: input
    id: character
    attributes:
      label: 캐릭터 이름
      description: 어떤 캐릭터의 CG인지 입력해주세요.
      placeholder: 예) 오하연
    validations:
      required: true
  - type: textarea
    id: pose-emotion
    attributes:
      label: 자세 & 표정
      description: 어떤 자세의 어떤 표정의 CG가 필요한지 설명해주세요.
      placeholder: 예) 턱을 괴면서 웃는 표정이 필요해요.
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: 레퍼런스
      description: 참고할 수 있는 레퍼런스가 있다면 알려주세요.
    validations:
      required: false
