[package]
name = "closure-macro"
version = "0.1.0"
edition = "2021"
namui = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.63"
quote = "1.0.29"
syn = { version = "2.0.22", features = ["full"] }
