[package]
name = "media"
version = "0.1.0"
edition = "2024"

# [package.metadata.namui]
# targets = ["x86_64-pc-windows-msvc"]

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
