#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
pub use luda_rpc::team::get_my_teams::*;
pub type OptionResult = Option<Result<Response, Error>>;
pub fn get_my_teams<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest>,
    dependencies: Deps,
) -> Sig<'a, OptionResult, &'a OptionResult> {
    server_rpc(ctx, request, dependencies)
}
pub fn get_my_teams_render<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest>,
    dependencies: Deps,
    on_loading: impl FnOnce(),
    on_err: impl FnOnce(&Error),
    on_res: impl FnOnce(&Response),
) {
    match get_my_teams(ctx, request, dependencies).as_ref() {
        Some(result) => match result {
            Ok(res) => on_res(res),
            Err(err) => on_err(err),
        },
        None => on_loading(),
    }
}
