[package]
name = "nimg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
jpegxl-rs = { version = "0.10.4", default-features = false, features = [
    "threads",
] }
