[package]
name = "namui-type"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "wasm32-wasi-web",
]

[features]
default = []
skia = ["dep:skia-safe"]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
num = { version = "0.4.0", features = ["std"] }
ordered-float = { version = "4.2.0", features = [
    "serde",
    "rkyv_32",
    "rkyv_ck",
] }
auto_ops = "0.3"
url = { version = "2.4.0", features = ["serde"] }
derive-macro = { path = "./derive-macro" }
postcard = { version = "1.0.6", features = ["use-std"] }
lru = "0.11.0"
anyhow = { version = "1.0.77", features = ["backtrace"] }
derivative = "2.2.0"
skia-safe = { path = "../third-party-forks/rust-skia/skia-safe", optional = true }
rkyv = { version = "0.7.44" }
rand = "0.8"
sha2 = "0.10"

[dev-dependencies]
float-cmp = "0.9"
serde_json = "1.0.117"
