[package]
name = "namui-type"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc"]

[features]
default = []
skia = ["dep:skia-safe"]
namui_internal = [
    # for namui crate internal use. Don't use this feature if you don't know about it.
]

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
num = { version = "0.4.0", features = ["std"] }
ordered-float = { version = "4.2.0", features = ["serde"] }
auto_ops = "0.3"
uuid = { version = "1.1", features = [
    "v4",
    "js",
    "macro-diagnostics",
    "serde",
] }
siphasher = "0.3"
url = { version = "2.4.0", features = ["serde"] }
derive-macro = { path = "./derive-macro" }
postcard = { version = "1.0.6", features = ["use-std"] }
lru = "0.11.0"
anyhow = { version = "1.0.77", features = ["backtrace"] }
derivative = "2.2.0"
web-time = "1.1.0"

[target.'cfg(not(target_family="wasm"))'.dependencies]
skia-safe = { version = "0.73.0", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
float-cmp = "0.9"
