[package]
name = "namui-type"
version = "0.1.0"
edition = "2024"

[package.metadata.namui]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "wasm32-wasi-web",
    "aarch64-apple-darwin",
]

[features]
default = []

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
num = { version = "0.4.0", features = ["std"] }
auto_ops = "0.3"
derive-macro = { path = "./derive-macro" }
lru = "0.11.0"
anyhow = { version = "1.0.77", features = ["backtrace"] }
derivative = "2.2.0"
rand = "0.8"
sha2 = "0.10"
chrono = "0.4.41"
bincode = "2.0.1"

[dev-dependencies]
float-cmp = "0.9"
serde_json = "1.0.117"
