[package]
name = "hooks"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[dependencies]
tokio = { version = "1", default-features = false, features = ["sync", "rt"] }
namui = { path = "../.." }
namui-prebuilt = { path = "../../../namui-prebuilt" }
closure-macro = { path = "./closure-macro" }
