#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
pub use luda_rpc::team_invite::join_team::*;
pub type OptionResult = Option<Result<Response, Error>>;
pub fn join_team<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest<'a>>,
    dependencies: Deps,
) -> Sig<'a, OptionResult, &'a OptionResult> {
    server_rpc(ctx, request, dependencies, 5u16)
}
pub fn join_team_render<'a, Deps: Dependencies + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest<'a>>,
    dependencies: Deps,
    on_loading: impl FnOnce(),
    on_err: impl FnOnce(&Error),
    on_res: impl FnOnce(&Response),
) {
    match join_team(ctx, request, dependencies).as_ref() {
        Some(result) => match result {
            Ok(res) => on_res(res),
            Err(err) => on_err(err),
        },
        None => on_loading(),
    }
}
impl ServerConnection {
    pub async fn join_team<'a>(
        &'a self,
        request: RefRequest<'a>,
    ) -> Result<Result<Response, Error>> {
        Ok(self
            .request(
                5u16,
                luda_rpc::rkyv::to_bytes::<_, 1024>(&request)
                    .unwrap()
                    .to_vec(),
            )
            .await?)
    }
}
