name: Restore docker image
runs:
  using: composite
  steps:
    - name: Pull inner image
      shell: bash
      run: time docker pull $INNER_IMAGE_NAME

    - name: Tag inner image as latest
      shell: bash
      run: time docker tag $INNER_IMAGE_NAME $LATEST_IMAGE_NAME
