[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
namui = { path = "../../namui", optional = true }
hyper = { version = "0.14", optional = true }
revert-json-patch = { path = "../revert-json-patch" }
migration = { path = "../migration" }
namui-type = { path = "../../namui-type" }
tokio = { version = "1.21", optional = true, features = ["time"] }
rand = { version = "0.8", optional = true }
bincode = { version = "1.3.3" }

[features]
client = ["dep:namui"]
server = ["dep:hyper", "dep:tokio", "dep:rand"]
