[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
namui = { path = "../../namui", optional = true }
hyper = { version = "0.14", optional = true }
base64 = "0.13"
json-patch = "0.2"

[features]
client = ["dep:namui"]
server = ["dep:hyper"]
