[package]
name = "rect"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
namui = { path = "../.." }

[dev-dependencies]
wasm-bindgen-test = "0.3"
