[package]
name = "rust-to-js"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
shlex = "1"
which = "7"

[dev-dependencies]