[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
document = { path = "../document" }

schema-0 = { path = "../0", package = "schema-0" }
