[package]
name = "canvas-kit-wasm-bindgen"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[package.metadata]
namui = true

[dependencies]
wasm-bindgen = { version = "0.2" }
js-sys = "0.3.55"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.web-sys]
version = "0.3"
features = ["HtmlCanvasElement"]
