[package]
name = "namui"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.63", features = ["serde-serialize"]  }
js-sys = "0.3.55"
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
wasm-bindgen-futures = "0.4.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3.17"
lazy_static = "1.4.0"
once_cell = "1.8.0"
serde_repr = "0.1"
tokio = { version = "1", default-features = false, features = ["sync"] }
console_error_panic_hook = { version = "0.1.6", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[dependencies.web-sys]
version = "0.3"
features = [
    "Window",
    "Document",
    "HtmlCanvasElement",
    "console",
    "Performance",
    "MouseEvent",
    "KeyboardEvent",
    "BinaryType",
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    "Crypto"
]
