#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
pub use luda_rpc::team::get_my_teams::*;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
pub fn get_my_teams<'a, Deps, Artifacts>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<(RefRequest, Artifacts)>,
    dependencies: Deps,
) -> SigRef<'a, Option<Result<(Response, <Artifacts as StaticOwned>::Owned), Error>>>
where
    Deps: Dependencies<'a> + 'a,
    Artifacts: StaticOwned,
{
    server_rpc(ctx, request, dependencies, 3u16)
}
pub fn get_my_teams_render<'a, Deps, Artifacts>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<(RefRequest, Artifacts)>,
    dependencies: Deps,
    on_loading: impl FnOnce(),
    on_err: impl FnOnce(&Error),
    on_res: impl FnOnce(&(Response, <Artifacts as StaticOwned>::Owned)),
) where
    Deps: Dependencies<'a> + 'a,
    Artifacts: StaticOwned,
{
    match get_my_teams(ctx, request, dependencies).as_ref() {
        Some(result) => match result {
            Ok(res) => on_res(res),
            Err(err) => on_err(err),
        },
        None => on_loading(),
    }
}
impl ServerConnection {
    pub async fn get_my_teams<'a>(&'a self, request: RefRequest) -> Result<Response, Error> {
        self.request(
            3u16,
            luda_rpc::rkyv::to_bytes::<_, 1024>(&request)
                .unwrap()
                .to_vec(),
        )
        .await
    }
}
pub fn make_get_my_teams_fn<'a, MakeRequestFn, ResponseFn, Artifacts>(
    ctx: &'a RenderCtx,
    make_request: MakeRequestFn,
    response_fn: ResponseFn,
) -> (impl FnOnce() + 'a, bool)
where
    MakeRequestFn: FnOnce() -> Option<(RefRequest, Artifacts)> + 'a,
    ResponseFn:
        FnOnce(Result<(Response, <Artifacts as StaticOwned>::Owned), Error>) + 'static + Send,
    Artifacts: StaticOwned,
{
    let on_progress = ctx.memo(|| Arc::new(AtomicBool::new(false)));
    let (server_connection, _) = ctx.atom(&SERVER_CONNECTION_ATOM);
    let server_connection = server_connection.clone_inner();
    let ret_on_progress = on_progress.load(Ordering::Relaxed);
    (
        move || {
            if on_progress.swap(true, Ordering::Relaxed) {
                return;
            }
            let Some((request, artifacts)) = make_request() else {
                on_progress.store(false, Ordering::Relaxed);
                return;
            };
            let bytes = luda_rpc::rkyv::to_bytes::<_, 1024>(&request)
                .unwrap()
                .to_vec();
            let owned_artifacts = artifacts.owned();
            let on_progress = on_progress.clone_inner();
            tokio::spawn(async move {
                let result = server_connection.request(3u16, bytes).await;
                on_progress.store(false, Ordering::Relaxed);
                response_fn(match result {
                    Ok(res) => Ok((res, owned_artifacts)),
                    Err(err) => Err(err),
                });
            });
        },
        ret_on_progress,
    )
}
