#![doc = r" This is Generated by rpc build.rs"]
use crate::{network::*, *};
pub use luda_rpc::team::get_my_teams::*;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
pub type OptionResult = Option<Result<Response, Error>>;
pub fn get_my_teams<'a, Deps: Dependencies<'a> + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest>,
    dependencies: Deps,
) -> Sig<'a, OptionResult, &'a OptionResult> {
    server_rpc(ctx, request, dependencies, 3u16)
}
pub fn get_my_teams_render<'a, Deps: Dependencies<'a> + 'a>(
    ctx: &'a RenderCtx,
    request: impl FnOnce(Deps) -> Option<RefRequest>,
    dependencies: Deps,
    on_loading: impl FnOnce(),
    on_err: impl FnOnce(&Error),
    on_res: impl FnOnce(&Response),
) {
    match get_my_teams(ctx, request, dependencies).as_ref() {
        Some(result) => match result {
            Ok(res) => on_res(res),
            Err(err) => on_err(err),
        },
        None => on_loading(),
    }
}
impl ServerConnection {
    pub async fn get_my_teams<'a>(&'a self, request: RefRequest) -> Result<Response, Error> {
        self.request(
            3u16,
            luda_rpc::rkyv::to_bytes::<_, 1024>(&request)
                .unwrap()
                .to_vec(),
        )
        .await
    }
}
pub fn make_create_team_fn<'a>(
    ctx: &'a RenderCtx,
    pre_request: impl FnOnce() -> Result<RefRequest, ()> + 'a,
    post_request: impl FnOnce(Result<Response, Error>) + 'static + Send,
) -> (impl FnOnce() + 'a, bool) {
    let on_progress = ctx.memo(|| Arc::new(AtomicBool::new(false)));
    let (server_connection, _) = ctx.atom(&SERVER_CONNECTION_ATOM);
    let server_connection = server_connection.clone_inner();
    let ret_on_progress = on_progress.load(Ordering::Relaxed);
    (
        move || {
            if on_progress.swap(true, Ordering::Relaxed) {
                return;
            }
            let Ok(request) = pre_request() else {
                on_progress.store(false, Ordering::Relaxed);
                return;
            };
            let bytes = luda_rpc::rkyv::to_bytes::<_, 1024>(&request)
                .unwrap()
                .to_vec();
            let on_progress = on_progress.clone_inner();
            tokio::spawn(async move {
                let result = server_connection.request(3u16, bytes).await;
                on_progress.store(false, Ordering::Relaxed);
                post_request(result);
            });
        },
        ret_on_progress,
    )
}
