[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
aws-sdk-s3 = "1.34.0"
quick_cache = "0.5.1"
tokio = { version = "1.38", features = ["rt", "time", "macros"] }
migration = { path = "../schema/migration" }
document = { path = "../schema/document" }
tar = "0.4.41"
lz4_flex = "0.11.3"
rusqlite = { version = "0.32.1", features = ["bundled"] }
nix = { version = "0.29.0", features = ["fs"] }
dashmap = "6.1.0"
bytes = "1.8.0"
