[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
tokio = { version = "1.38", features = ["rt", "time", "macros", "sync"] }
# migration = { path = "../schema/migration" }
document = { path = "../schema/document" }
bytes = "1"
rayon = "1.10.0"
crc = "3.2.1"
bptree = { path = "../../bptree" }
futures = "0.3.31"
uuid = { version = "1.11.0", features = ["v4"] }
libc = "0.2.162"
arc-swap = "1.7.1"

[profile.release]
debug = true
