[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.86", features = ["backtrace"] }
# aws-sdk-s3 = "1.34.0"
quick_cache = "0.5.1"
tokio = { version = "1.38", features = ["rt", "time", "macros", "sync"] }
migration = { path = "../schema/migration" }
document = { path = "../schema/document" }
tar = "0.4.41"
lz4_flex = "0.11.3"
rusqlite = { version = "0.32.1", features = ["bundled"] }
bytes = "1.8.0"
rayon = "1.10.0"
crc = "3.2.1"
libc = "0.2.161"

[profile.release]
debug = true
