use crate::*;

#[derive(Clone, Copy, State)]
pub enum MonsterKind {
    Mob01,
    Mob02,
    Mob03,
    Mob04,
    Mob05,
    Mob06,
    Mob07,
    Mob08,
    Mob09,
    Mob10,
    Mob11,
    Mob12,
    Mob13,
    Mob14,
    Mob15,
    Named01,
    Named02,
    Named03,
    Named04,
    Named05,
    Named06,
    Named07,
    Named08,
    Named09,
    Named10,
    Named11,
    Named12,
    Named13,
    Named14,
    Named15,
    Named16,
    Boss01,
    Boss02,
    Boss03,
    Boss04,
    Boss05,
    Boss06,
    Boss07,
    Boss08,
    Boss09,
    Boss10,
    Boss11,
}

impl MonsterKind {
    pub fn image(self) -> Image {
        match self {
            MonsterKind::Mob01 => crate::asset::image::monster::MOB01,
            MonsterKind::Mob02 => crate::asset::image::monster::MOB02,
            MonsterKind::Mob03 => crate::asset::image::monster::MOB03,
            MonsterKind::Mob04 => crate::asset::image::monster::MOB04,
            MonsterKind::Mob05 => crate::asset::image::monster::MOB05,
            MonsterKind::Mob06 => crate::asset::image::monster::MOB06,
            MonsterKind::Mob07 => crate::asset::image::monster::MOB07,
            MonsterKind::Mob08 => crate::asset::image::monster::MOB08,
            MonsterKind::Mob09 => crate::asset::image::monster::MOB09,
            MonsterKind::Mob10 => crate::asset::image::monster::MOB10,
            MonsterKind::Mob11 => crate::asset::image::monster::MOB11,
            MonsterKind::Mob12 => crate::asset::image::monster::MOB12,
            MonsterKind::Mob13 => crate::asset::image::monster::MOB13,
            MonsterKind::Mob14 => crate::asset::image::monster::MOB14,
            MonsterKind::Mob15 => crate::asset::image::monster::MOB15,
            MonsterKind::Named01 => crate::asset::image::monster::NAMED01,
            MonsterKind::Named02 => crate::asset::image::monster::NAMED02,
            MonsterKind::Named03 => crate::asset::image::monster::NAMED03,
            MonsterKind::Named04 => crate::asset::image::monster::NAMED04,
            MonsterKind::Named05 => crate::asset::image::monster::NAMED05,
            MonsterKind::Named06 => crate::asset::image::monster::NAMED06,
            MonsterKind::Named07 => crate::asset::image::monster::NAMED07,
            MonsterKind::Named08 => crate::asset::image::monster::NAMED08,
            MonsterKind::Named09 => crate::asset::image::monster::NAMED09,
            MonsterKind::Named10 => crate::asset::image::monster::NAMED10,
            MonsterKind::Named11 => crate::asset::image::monster::NAMED11,
            MonsterKind::Named12 => crate::asset::image::monster::NAMED12,
            MonsterKind::Named13 => crate::asset::image::monster::NAMED13,
            MonsterKind::Named14 => crate::asset::image::monster::NAMED14,
            MonsterKind::Named15 => crate::asset::image::monster::NAMED15,
            MonsterKind::Named16 => crate::asset::image::monster::NAMED16,
            MonsterKind::Boss01 => crate::asset::image::monster::BOSS01,
            MonsterKind::Boss02 => crate::asset::image::monster::BOSS02,
            MonsterKind::Boss03 => crate::asset::image::monster::BOSS03,
            MonsterKind::Boss04 => crate::asset::image::monster::BOSS04,
            MonsterKind::Boss05 => crate::asset::image::monster::BOSS05,
            MonsterKind::Boss06 => crate::asset::image::monster::BOSS06,
            MonsterKind::Boss07 => crate::asset::image::monster::BOSS07,
            MonsterKind::Boss08 => crate::asset::image::monster::BOSS08,
            MonsterKind::Boss09 => crate::asset::image::monster::BOSS09,
            MonsterKind::Boss10 => crate::asset::image::monster::BOSS10,
            MonsterKind::Boss11 => crate::asset::image::monster::BOSS11,
        }
    }

    pub fn emoji(&self) -> &str {
        match self {
            MonsterKind::Mob01 => "🌱",
            MonsterKind::Mob02 => "🌿",
            MonsterKind::Mob03 => "🌵",
            MonsterKind::Mob04 => "🍀",
            MonsterKind::Mob05 => "💮",
            MonsterKind::Mob06 => "🥬",
            MonsterKind::Mob07 => "🥒",
            MonsterKind::Mob08 => "🫐",
            MonsterKind::Mob09 => "🍇",
            MonsterKind::Mob10 => "🫑",
            MonsterKind::Mob11 => "🍒",
            MonsterKind::Mob12 => "🐝",
            MonsterKind::Mob13 => "🪲",
            MonsterKind::Mob14 => "🪳",
            MonsterKind::Mob15 => "🐨",
            MonsterKind::Named01 => "🌺",
            MonsterKind::Named02 => "🌸",
            MonsterKind::Named03 => "🥕",
            MonsterKind::Named04 => "🌽",
            MonsterKind::Named05 => "🍊",
            MonsterKind::Named06 => "🍄",
            MonsterKind::Named07 => "🍎",
            MonsterKind::Named08 => "🦂",
            MonsterKind::Named09 => "🐜",
            MonsterKind::Named10 => "🦟",
            MonsterKind::Named11 => "🦊",
            MonsterKind::Named12 => "🐺",
            MonsterKind::Named13 => "🦏",
            MonsterKind::Named14 => "🐻",
            MonsterKind::Named15 => "🐻‍❄️",
            MonsterKind::Named16 => "🦅",
            MonsterKind::Boss01 => "🥦",
            MonsterKind::Boss02 => "🦋",
            MonsterKind::Boss03 => "🐞",
            MonsterKind::Boss04 => "🦁",
            MonsterKind::Boss05 => "🦝",
            MonsterKind::Boss06 => "🐮",
            MonsterKind::Boss07 => "🐯",
            MonsterKind::Boss08 => "🐼",
            MonsterKind::Boss09 => "🦍",
            MonsterKind::Boss10 => "🦖",
            MonsterKind::Boss11 => "🦚",
        }
    }
}
