use crate::*;

#[derive(Clone, Copy, State)]
pub enum MonsterKind {
    Mob01,
    Mob02,
    Mob03,
    Mob04,
    Mob05,
    Mob06,
    Mob07,
    Mob08,
    Mob09,
    Mob10,
    Mob11,
    Mob12,
    Mob13,
    Mob14,
    Mob15,
    Named01,
    Named02,
    Named03,
    Named04,
    Named05,
    Named06,
    Named07,
    Named08,
    Named09,
    Named10,
    Named11,
    Named12,
    Named13,
    Named14,
    Named15,
    Named16,
    Boss01,
    Boss02,
    Boss03,
    Boss04,
    Boss05,
    Boss06,
    Boss07,
    Boss08,
    Boss09,
    Boss10,
    Boss11,
}

impl MonsterKind {
    pub fn emoji(&self) -> &str {
        match self {
            MonsterKind::Mob01 => "🌱",
            MonsterKind::Mob02 => "🌿",
            MonsterKind::Mob03 => "🌵",
            MonsterKind::Mob04 => "🍀",
            MonsterKind::Mob05 => "💮",
            MonsterKind::Mob06 => "🥬",
            MonsterKind::Mob07 => "🥒",
            MonsterKind::Mob08 => "🫐",
            MonsterKind::Mob09 => "🍇",
            MonsterKind::Mob10 => "🫑",
            MonsterKind::Mob11 => "🍒",
            MonsterKind::Mob12 => "🐝",
            MonsterKind::Mob13 => "🪲",
            MonsterKind::Mob14 => "🪳",
            MonsterKind::Mob15 => "🐨",
            MonsterKind::Named01 => "🌺",
            MonsterKind::Named02 => "🌸",
            MonsterKind::Named03 => "🥕",
            MonsterKind::Named04 => "🌽",
            MonsterKind::Named05 => "🍊",
            MonsterKind::Named06 => "🍄",
            MonsterKind::Named07 => "🍎",
            MonsterKind::Named08 => "🦂",
            MonsterKind::Named09 => "🐜",
            MonsterKind::Named10 => "🦟",
            MonsterKind::Named11 => "🦊",
            MonsterKind::Named12 => "🐺",
            MonsterKind::Named13 => "🦏",
            MonsterKind::Named14 => "🐻",
            MonsterKind::Named15 => "🐻‍❄️",
            MonsterKind::Named16 => "🦅",
            MonsterKind::Boss01 => "🥦",
            MonsterKind::Boss02 => "🦋",
            MonsterKind::Boss03 => "🐞",
            MonsterKind::Boss04 => "🦁",
            MonsterKind::Boss05 => "🦝",
            MonsterKind::Boss06 => "🐮",
            MonsterKind::Boss07 => "🐯",
            MonsterKind::Boss08 => "🐼",
            MonsterKind::Boss09 => "🦍",
            MonsterKind::Boss10 => "🦖",
            MonsterKind::Boss11 => "🦚",
        }
    }

    pub fn asset_id(&self) -> &'static str {
        match self {
            MonsterKind::Mob01 => "mob01",
            MonsterKind::Mob02 => "mob02",
            MonsterKind::Mob03 => "mob03",
            MonsterKind::Mob04 => "mob04",
            MonsterKind::Mob05 => "mob05",
            MonsterKind::Mob06 => "mob06",
            MonsterKind::Mob07 => "mob07",
            MonsterKind::Mob08 => "mob08",
            MonsterKind::Mob09 => "mob09",
            MonsterKind::Mob10 => "mob10",
            MonsterKind::Mob11 => "mob11",
            MonsterKind::Mob12 => "mob12",
            MonsterKind::Mob13 => "mob13",
            MonsterKind::Mob14 => "mob14",
            MonsterKind::Mob15 => "mob15",
            MonsterKind::Named01 => "named01",
            MonsterKind::Named02 => "named02",
            MonsterKind::Named03 => "named03",
            MonsterKind::Named04 => "named04",
            MonsterKind::Named05 => "named05",
            MonsterKind::Named06 => "named06",
            MonsterKind::Named07 => "named07",
            MonsterKind::Named08 => "named08",
            MonsterKind::Named09 => "named09",
            MonsterKind::Named10 => "named10",
            MonsterKind::Named11 => "named11",
            MonsterKind::Named12 => "named12",
            MonsterKind::Named13 => "named13",
            MonsterKind::Named14 => "named14",
            MonsterKind::Named15 => "named15",
            MonsterKind::Named16 => "named16",
            MonsterKind::Boss01 => "boss01",
            MonsterKind::Boss02 => "boss02",
            MonsterKind::Boss03 => "boss03",
            MonsterKind::Boss04 => "boss04",
            MonsterKind::Boss05 => "boss05",
            MonsterKind::Boss06 => "boss06",
            MonsterKind::Boss07 => "boss07",
            MonsterKind::Boss08 => "boss08",
            MonsterKind::Boss09 => "boss09",
            MonsterKind::Boss10 => "boss10",
            MonsterKind::Boss11 => "boss11",
        }
    }
}
