name: Run namui test
inputs:
  target:
    required: true
  path:
    required: true
env:
  RUSTFLAGS: -D warnings
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.path }}/target/
        key: ${{ runner.os }}-cargo-${{ inputs.path }}-${{ inputs.target }}-${{ hashFiles(format('{0}/Cargo.lock', inputs.path)) }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.path }}-${{ inputs.target }}-
          ${{ runner.os }}-cargo-${{ inputs.path }}-
          ${{ runner.os }}-cargo-

    - name: Test
      shell: bash
      run: time namui test ${{ inputs.target }} -m ${{ inputs.path }}/Cargo.toml

    - name: Did you push Cargo.lock
      shell: bash
      run: |
        if [[ $(git diff --name-only) ]]; then
            echo "::error::File change detected. If it's Cargo.lock, you should add it into git"
            echo  "::error::$(git diff --name-only)"
            exit 1
        else
            echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
        fi

    - name: Fmt
      shell: bash
      run: cargo fmt --manifest-path ${{ inputs.path }}/Cargo.toml

    - name: Did you forget run fmt
      shell: bash
      run: |
        if [[ $(git diff --name-only) ]]; then
            echo "::error::File change detected. Please run 'cargo fmt' before push"
            echo  "::error::$(git diff --name-only)"
            exit 1
        else
            echo "Good. Cargo.lock is up to date (or it ignored by gitignore)"
        fi

    - name: Clippy
      shell: bash
      run: cargo clippy --manifest-path ${{ inputs.path }}/Cargo.toml -- -D warnings

    - name: Did you forget run cargo clippy
      shell: bash
      run: |
        if [[ $? ]]; then
            echo "::error::Clippy failed. Please check code with 'cargo clippy' before push"
            exit 1
        else
            echo "Good. Clippy passed"
        fi
