name: Run namui test
inputs:
  target:
    required: true
  path:
    required: true
runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          **/target/
        key: ${{ runner.os }}-cargo-${{ inputs.path }}-${{ inputs.target }}-${{ hashFiles('${{ inputs.path }}/Cargo.lock') }}

    - name: Test
      shell: bash
      run: time namui test ${{ inputs.target }} -m ${{ inputs.path }}/Cargo.toml

    - name: Check up to date Cargo.lock checked
      uses: technote-space/get-diff-action@v6
      with:
        FILES: |
          Cargo.lock

    - name: Confirm Cargo.lock
      if: env.GIT_DIFF
      shell: bash
      run: printf "::error::File change detected. If it's Cargo.lock, you should add it into git\n" && git diff --name-only && exit 1
