name: Publish and install for-all-projects
env:
  RUSTFLAGS: -D warnings
runs:
  using: composite
  steps:
    - uses: SebRollen/toml-action@v1.0.2
      id: for-all-projects-cargo-toml
      with:
        file: for-all-projects/Cargo.toml
        field: package.version

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/for-all-projects
        key: ${{ runner.os }}-for-all-projects-${{ steps.for-all-projects-cargo-toml.outputs.value }}

    - name: Install for-all-projects
      shell: bash
      run: if [ ! -f ~/.cargo/bin/for-all-projects ]; then cargo install for-all-projects; fi
