[package]
name = "bptree"
version = "0.1.0"
edition = "2024"

[package.metadata.namui]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
arc-swap = "1"
bytes = "1"
crc = "3"
futures = "0.3.31"
libc = "0.2"
thiserror = "2"
tokio = { version = "1", features = ["fs", "macros", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = [
    "macros",
    "rt",
    "sync",
    "time",
    "rt-multi-thread",
] }
