[package]
name = "bptree"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
arc-swap = "1"
bytes = "1"
crc = "3"
futures = "0.3.31"
libc = "0.2"
pin-project = "1"
tokio = { version = "1", features = ["macros", "rt", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = [
    "macros",
    "rt",
    "sync",
    "time",
    "rt-multi-thread",
] }
