[package]
name = "namui-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
cli_debug = []

[dependencies]
clap = { version = "4.2.0", features = ["derive"] }
futures = "0.3.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.72"
cargo_metadata = "0.11.0"
notify = "6"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
webbrowser = "0.5.5"
regex = "1.5.4"
wsl = "0.1.0"
fs_extra = "1.3"
namui-user-config = { path = "../namui-user-config" }
tokio-util = { version = "0.7.1", features = ["codec"] }
urlencoding = "2.1"
clap_complete = "4.2.0"
anyhow = { version = "1.0.71", features = ["backtrace"] }
mime_guess = "2.0.4"
itertools = "0.11.0"
pathdiff = "0.2.1"
walkdir = "2.4.0"

[build-dependencies]
clap = { version = "*", features = ["derive"] }
clap_complete = "*"
serde = { version = "*", features = ["derive"] }
namui-user-config = { path = "../namui-user-config" }
anyhow = { version = "1.0.71", features = ["backtrace"] }
reqwest = { version = "0.12.4", features = ["blocking"] }
flate2 = "1.0"
tar = "0.4.40"
