[package]
name = "namui-animation-editor-sample"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = true
opt-level = 2

[dependencies]
namui = { path = "../../namui" }
namui-animation-editor = { path = ".." }

[dev-dependencies]
wasm-bindgen-test = "0.3"
