[package]
name = "namui-animation-editor-sample"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 3

[profile.dev]
lto = true
opt-level = 2

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
namui = { path = "../../namui" }
namui-animation-editor = { path = ".." }