[package]
name = "mk-workflows"
version = "0.1.0"
authors = ["Armin Sander <armin@replicator.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
