[package]
name = "type-macro"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[dependencies]
namui = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
