[package]
name = "namui-skia"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[features]
default = []
window = ["skia-safe/d3d", "windows"]


[dependencies]
windows = { version = "0.52.0", features = [
    "Win32",
    "Win32_Graphics",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Foundation",
    "Win32_Graphics_Dxgi_Common",
], optional = true }
anyhow = "1.0.75"
namui-type = { path = "../../namui-type" }
serde = { version = "1.0.183", features = ["derive"] }
skia-safe = { path = "../../../sambashare/rust-skia/skia-safe", optional = true }

[dev-dependencies]

[target.'cfg(target_family="wasm")'.dependencies]
canvas-kit-wasm-bindgen = { path = "../canvas-kit-wasm-bindgen" }
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.64", features = [
    "ImageBitmap",
    "OffscreenCanvas",
    "OffscreenCanvasRenderingContext2d",
    "Blob",
] }
wasm-bindgen-futures = "0.4.37"

[target.'cfg(target_family="wasm")'.dev-dependencies]
wasm-bindgen-test = "0.2"

[target.'cfg(not(target_family="wasm"))'.dependencies]


[target.'cfg(not(target_family="wasm"))'.dev-dependencies]
