name: Rustup update
env:
  RUSTFLAGS: -D warnings
runs:
  using: composite
  steps:
    - name: Rustup update
      shell: bash
      run: |
        rustup update
        CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV
