pub(super) mod battery;
pub(super) mod brush;
pub(super) mod cactus;
pub(super) mod club_sword;
pub(super) mod copier;
pub(super) mod eraser;
pub(super) mod fountain_pen;
pub(super) mod long_sword;
pub(super) mod mace;
pub(super) mod magic_wand;
pub(super) mod magnet;
pub(super) mod pliers;
pub(super) mod screwdriver;
pub(super) mod spinning_top;
pub(super) mod staff;
pub(super) mod support;
pub(super) mod tricycle;

pub(crate) use battery::DEFINITION as BATTERY;
pub(crate) use brush::DEFINITION as BRUSH;
pub(crate) use cactus::DEFINITION as CACTUS;
pub(crate) use club_sword::DEFINITION as CLUB_SWORD;
pub(crate) use copier::DEFINITION as COPIER;
pub(crate) use eraser::DEFINITION as ERASER;
pub(crate) use fountain_pen::DEFINITION as FOUNTAIN_PEN;
pub(crate) use long_sword::DEFINITION as LONG_SWORD;
pub(crate) use mace::DEFINITION as MACE;
pub(crate) use magic_wand::DEFINITION as MAGIC_WAND;
pub(crate) use magnet::DEFINITION as MAGNET;
pub(crate) use pliers::DEFINITION as PLIERS;
pub(crate) use screwdriver::DEFINITION as SCREWDRIVER;
pub(crate) use spinning_top::DEFINITION as SPINNING_TOP;
pub(crate) use staff::DEFINITION as STAFF;
pub(crate) use tricycle::DEFINITION as TRICYCLE;
