version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  open-pull-requests-limit: 10
  assignees:
  - pragmatrix
  ignore:
  - dependency-name: foreign-types
    versions:
    - "> 0.5.0"
  - dependency-name: clang-sys
    versions:
    - 1.0.3
    - 1.1.0
    - 1.1.1
