[package]
name = "beat-maker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aubio = "0.2.1"
microdsp = "0.1.2"
opus = "0.3.0"
symphonia = "0.5.3"
