export function appendBaseSection(rs: string): string {
    rs += `use namui::*;\n\n`;
    rs += `fn rect(x: f32, y: f32, w: f32, h: f32) -> Rect<Px> {\n`;
    rs += `    Rect::Xywh { x: px(x), y: px(y), width: px(w), height: px(h) }\n`;
    rs += `}\n\n`;

    rs += `const LINE_SPRITE_W: f32 = 1024.0;\n`;
    rs += `const LINE_SPRITE_H: f32 = 16.0;\n\n`;

    rs += `pub fn centered_sprite(\n`;
    rs += `    src_rect: Rect<Px>,\n`;
    rs += `    cx: Px,\n`;
    rs += `    cy: Px,\n`;
    rs += `    scale: f32,\n`;
    rs += `    color: Option<Color>,\n`;
    rs += `) -> ImageSprite {\n`;
    rs += `    let sw = src_rect.width().as_f32();\n`;
    rs += `    let sh = src_rect.height().as_f32();\n`;
    rs += `    ImageSprite {\n`;
    rs += `        src_rect,\n`;
    rs += `        xform: RSXform {\n`;
    rs += `            scos: scale,\n`;
    rs += `            ssin: 0.0,\n`;
    rs += `            tx: cx - px(scale * sw / 2.0),\n`;
    rs += `            ty: cy - px(scale * sh / 2.0),\n`;
    rs += `        },\n`;
    rs += `        color,\n`;
    rs += `    }\n`;
    rs += `}\n\n`;

    rs += `pub fn centered_rotated_sprite(\n`;
    rs += `    src_rect: Rect<Px>,\n`;
    rs += `    cx: Px,\n`;
    rs += `    cy: Px,\n`;
    rs += `    scale: f32,\n`;
    rs += `    angle_rad: f32,\n`;
    rs += `    color: Option<Color>,\n`;
    rs += `) -> ImageSprite {\n`;
    rs += `    let sw = src_rect.width().as_f32();\n`;
    rs += `    let sh = src_rect.height().as_f32();\n`;
    rs += `    let cos_a = angle_rad.cos();\n`;
    rs += `    let sin_a = angle_rad.sin();\n`;
    rs += `    let scos = scale * cos_a;\n`;
    rs += `    let ssin = scale * sin_a;\n`;
    rs += `    ImageSprite {\n`;
    rs += `        src_rect,\n`;
    rs += `        xform: RSXform {\n`;
    rs += `            scos,\n`;
    rs += `            ssin,\n`;
    rs += `            tx: cx - px(scos * sw / 2.0 - ssin * sh / 2.0),\n`;
    rs += `            ty: cy - px(ssin * sw / 2.0 + scos * sh / 2.0),\n`;
    rs += `        },\n`;
    rs += `        color,\n`;
    rs += `    }\n`;
    rs += `}\n\n`;

    rs += `pub fn line_sprite(\n`;
    rs += `    start_x: Px,\n`;
    rs += `    start_y: Px,\n`;
    rs += `    end_x: Px,\n`;
    rs += `    end_y: Px,\n`;
    rs += `    thickness: f32,\n`;
    rs += `    color: Option<Color>,\n`;
    rs += `) -> Option<ImageSprite> {\n`;
    rs += `    line_sprite_from_rect(\n`;
    rs += `        Rect::Xywh { x: px(0.0), y: px(0.0), width: px(LINE_SPRITE_W), height: px(LINE_SPRITE_H) },\n`;
    rs += `        start_x,\n`;
    rs += `        start_y,\n`;
    rs += `        end_x,\n`;
    rs += `        end_y,\n`;
    rs += `        thickness,\n`;
    rs += `        color,\n`;
    rs += `    )\n`;
    rs += `}\n\n`;

    rs += `pub fn line_sprite_from_rect(\n`;
    rs += `    src_base_rect: Rect<Px>,\n`;
    rs += `    start_x: Px,\n`;
    rs += `    start_y: Px,\n`;
    rs += `    end_x: Px,\n`;
    rs += `    end_y: Px,\n`;
    rs += `    thickness: f32,\n`;
    rs += `    color: Option<Color>,\n`;
    rs += `) -> Option<ImageSprite> {\n`;
    rs += `    let dx = (end_x - start_x).as_f32();\n`;
    rs += `    let dy = (end_y - start_y).as_f32();\n`;
    rs += `    let length = (dx * dx + dy * dy).sqrt();\n`;
    rs += `    let base_h = src_base_rect.height().as_f32();\n`;
    rs += `    let base_w = src_base_rect.width().as_f32();\n`;
    rs += `    if length < 0.001 || thickness < 0.001 {\n`;
    rs += `        return None;\n`;
    rs += `    }\n`;
    rs += `    let angle = dy.atan2(dx);\n`;
    rs += `    let scale = thickness / base_h;\n`;
    rs += `    let src_w = (length / scale).min(base_w);\n`;
    rs += `    let cos_a = angle.cos();\n`;
    rs += `    let sin_a = angle.sin();\n`;
    rs += `    let scos = scale * cos_a;\n`;
    rs += `    let ssin = scale * sin_a;\n`;
    rs += `    let half_h = base_h / 2.0;\n`;
    rs += `    Some(ImageSprite {\n`;
    rs += `        src_rect: Rect::Xywh {\n`;
    rs += `            x: src_base_rect.left(),\n`;
    rs += `            y: src_base_rect.top(),\n`;
    rs += `            width: px(src_w),\n`;
    rs += `            height: px(base_h),\n`;
    rs += `        },\n`;
    rs += `        xform: RSXform {\n`;
    rs += `            scos,\n`;
    rs += `            ssin,\n`;
    rs += `            tx: start_x + px(ssin * half_h),\n`;
    rs += `            ty: start_y - px(scos * half_h),\n`;
    rs += `        },\n`;
    rs += `        color,\n`;
    rs += `    })\n`;
    rs += `}\n\n`;

    return rs;
}
