[package]
name = "rust-to-js"
version = "0.1.0"
edition = "2024"

[package.metadata.rust-analyzer]
rustc_private=true

[dependencies]
rustc-build-sysroot = "0.5.11"

[dev-dependencies]
rquickjs = "0.9.0"
