[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpc = { path = "../rpc", features = ["server"] }
lambda-web = { path = "./lambda-web", features = ["hyper"] }
tokio = { version = "1.20", features = ["fs"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_dynamo = { version = "4.0", features = ["aws-sdk-dynamodb+0_17"] }
once_cell = "1.13"
aws-sdk-dynamodb = "0.17"
aws-config = "0.47"
aws-types = "0.47"
aws-sdk-s3 = "0.17"
yrs = "0.11"
nanoid = "0.4"
futures = "0.3"
chrono = "0.4"
