[package]
name = "idol-club"
version = "0.1.0"
edition = "2024"

[package.metadata]
namui = true

[dependencies]
namui = { path = "../namui/namui" }
namui-prebuilt = { path = "../namui/namui-prebuilt" }
