name: Publish and install for-all-projects
env:
  RUSTFLAGS: -D warnings
runs:
  using: composite
  steps:
    - uses: Swatinem/rust-cache@v2
      with:
        prefix-key: for-all-projects
        cache-directories: for-all-projects

    - name: Build for-all-projects
      shell: bash
      working-directory: for-all-projects
      run: cargo build

    - name: Symlink for-all-projects
      shell: bash
      run: |
        rm -f ~/.cargo/bin/for-all-projects
        ln -s $(pwd)/for-all-projects/target/debug/for-all-projects ~/.cargo/bin/for-all-projects
