[player]
max_hp = 60.0
starting_gold = 100
starting_hp = 60.0
base_dice_chance = 3
max_stages = 50
base_hand_slots = 5

[monsters.stats.Mob01]
base_hp = 67.6574478149414
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob02]
base_hp = 80.45519256591797
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob03]
base_hp = 99.07583618164063
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob04]
base_hp = 122.85478973388672
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob05]
base_hp = 102.9825439453125
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob06]
base_hp = 149.23406982421875
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob07]
base_hp = 67.43571472167969
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob08]
base_hp = 95.64513397216797
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob09]
base_hp = 144.77818298339844
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob10]
base_hp = 99.04206085205078
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob11]
base_hp = 469.0461120605469
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob12]
base_hp = 256.0854187011719
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob13]
base_hp = 670.5013427734375
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob14]
base_hp = 621.191162109375
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob15]
base_hp = 708.9054565429688
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob16]
base_hp = 1379.2034912109375
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob17]
base_hp = 1129.679443359375
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob18]
base_hp = 1900.701904296875
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob19]
base_hp = 2836.024658203125
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob20]
base_hp = 2127.11572265625
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob21]
base_hp = 12908.0849609375
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob22]
base_hp = 4764.39111328125
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob23]
base_hp = 22701.80859375
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob24]
base_hp = 18348.47265625
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob25]
base_hp = 5222.4931640625
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob26]
base_hp = 86653.6171875
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob27]
base_hp = 22511.947265625
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob28]
base_hp = 110594.3828125
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob29]
base_hp = 133263.109375
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob30]
base_hp = 37800.3515625
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob31]
base_hp = 309085.09375
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob32]
base_hp = 112529.8671875
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob33]
base_hp = 428018.28125
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob34]
base_hp = 501495.375
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob35]
base_hp = 179908.015625
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob36]
base_hp = 2310131.75
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob37]
base_hp = 578899.625
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob38]
base_hp = 3118856.75
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob39]
base_hp = 3838416.25
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob40]
base_hp = 804806.5
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob41]
base_hp = 13496747.0
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob42]
base_hp = 2710226.0
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Mob43]
base_hp = 24543882.0
velocity_mul = 0.75
damage = 1.0
reward = 3

[monsters.stats.Mob44]
base_hp = 30274130.0
velocity_mul = 1.25
damage = 1.0
reward = 3

[monsters.stats.Mob45]
base_hp = 4426441.5
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob46]
base_hp = 9086778.0
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob47]
base_hp = 8584616.0
velocity_mul = 1.0
damage = 4.0
reward = 3

[monsters.stats.Mob48]
base_hp = 25220472.0
velocity_mul = 0.75
damage = 2.0
reward = 3

[monsters.stats.Mob49]
base_hp = 31976610.0
velocity_mul = 1.25
damage = 2.0
reward = 3

[monsters.stats.Mob50]
base_hp = 11561208.0
velocity_mul = 1.0
damage = 2.0
reward = 3

[monsters.stats.Boss01]
base_hp = 154.47381591796875
velocity_mul = 1.0
damage = 5.0
reward = 25

[monsters.stats.Boss02]
base_hp = 148.56309509277344
velocity_mul = 1.0
damage = 5.0
reward = 50

[monsters.stats.Boss03]
base_hp = 1063.358154296875
velocity_mul = 1.0
damage = 5.0
reward = 50

[monsters.stats.Boss04]
base_hp = 3190.673583984375
velocity_mul = 1.0
damage = 7.0
reward = 50

[monsters.stats.Boss05]
base_hp = 7833.73974609375
velocity_mul = 1.0
damage = 7.0
reward = 50

[monsters.stats.Boss06]
base_hp = 56700.52734375
velocity_mul = 1.0
damage = 7.0
reward = 50

[monsters.stats.Boss07]
base_hp = 269862.03125
velocity_mul = 1.0
damage = 10.0
reward = 50

[monsters.stats.Boss08]
base_hp = 1207209.75
velocity_mul = 1.0
damage = 10.0
reward = 50

[monsters.stats.Boss09]
base_hp = 6639662.0
velocity_mul = 1.0
damage = 10.0
reward = 50

[monsters.stats.Boss10]
base_hp = 13630167.0
velocity_mul = 1.0
damage = 10.0
reward = 50

[monsters.stats.Boss11]
base_hp = 12876924.0
velocity_mul = 1.0
damage = 15.0
reward = 50

[monsters.stats.Boss12]
base_hp = 37830708.0
velocity_mul = 0.75
damage = 10.0
reward = 50

[monsters.stats.Boss13]
base_hp = 47964916.0
velocity_mul = 1.25
damage = 10.0
reward = 50

[monsters.stats.Boss14]
base_hp = 17341812.0
velocity_mul = 1.0
damage = 10.0
reward = 50

[[monsters.stage_waves]]
stage = 1

[[monsters.stage_waves.entries]]
kind = "Mob01"
count = 5

[[monsters.stage_waves]]
stage = 2

[[monsters.stage_waves.entries]]
kind = "Mob02"
count = 5

[[monsters.stage_waves]]
stage = 3

[[monsters.stage_waves.entries]]
kind = "Mob03"
count = 5

[[monsters.stage_waves]]
stage = 4

[[monsters.stage_waves.entries]]
kind = "Mob04"
count = 5

[[monsters.stage_waves]]
stage = 5

[[monsters.stage_waves.entries]]
kind = "Mob05"
count = 5

[[monsters.stage_waves.entries]]
kind = "Boss01"
count = 1

[[monsters.stage_waves]]
stage = 6

[[monsters.stage_waves.entries]]
kind = "Mob06"
count = 7

[[monsters.stage_waves]]
stage = 7

[[monsters.stage_waves.entries]]
kind = "Mob07"
count = 7

[[monsters.stage_waves]]
stage = 8

[[monsters.stage_waves.entries]]
kind = "Mob08"
count = 7

[[monsters.stage_waves]]
stage = 9

[[monsters.stage_waves.entries]]
kind = "Mob09"
count = 7

[[monsters.stage_waves]]
stage = 10

[[monsters.stage_waves.entries]]
kind = "Mob10"
count = 7

[[monsters.stage_waves.entries]]
kind = "Boss02"
count = 1

[[monsters.stage_waves]]
stage = 11

[[monsters.stage_waves.entries]]
kind = "Mob11"
count = 9

[[monsters.stage_waves]]
stage = 12

[[monsters.stage_waves.entries]]
kind = "Mob12"
count = 9

[[monsters.stage_waves]]
stage = 13

[[monsters.stage_waves.entries]]
kind = "Mob13"
count = 9

[[monsters.stage_waves]]
stage = 14

[[monsters.stage_waves.entries]]
kind = "Mob14"
count = 9

[[monsters.stage_waves]]
stage = 15

[[monsters.stage_waves.entries]]
kind = "Mob15"
count = 8

[[monsters.stage_waves.entries]]
kind = "Boss03"
count = 1

[[monsters.stage_waves]]
stage = 16

[[monsters.stage_waves.entries]]
kind = "Mob16"
count = 10

[[monsters.stage_waves]]
stage = 17

[[monsters.stage_waves.entries]]
kind = "Mob17"
count = 10

[[monsters.stage_waves]]
stage = 18

[[monsters.stage_waves.entries]]
kind = "Mob18"
count = 10

[[monsters.stage_waves]]
stage = 19

[[monsters.stage_waves.entries]]
kind = "Mob19"
count = 10

[[monsters.stage_waves]]
stage = 20

[[monsters.stage_waves.entries]]
kind = "Mob20"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss04"
count = 1

[[monsters.stage_waves]]
stage = 21

[[monsters.stage_waves.entries]]
kind = "Mob21"
count = 11

[[monsters.stage_waves]]
stage = 22

[[monsters.stage_waves.entries]]
kind = "Mob22"
count = 11

[[monsters.stage_waves]]
stage = 23

[[monsters.stage_waves.entries]]
kind = "Mob23"
count = 11

[[monsters.stage_waves]]
stage = 24

[[monsters.stage_waves.entries]]
kind = "Mob24"
count = 11

[[monsters.stage_waves]]
stage = 25

[[monsters.stage_waves.entries]]
kind = "Mob25"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss05"
count = 1

[[monsters.stage_waves]]
stage = 26

[[monsters.stage_waves.entries]]
kind = "Mob26"
count = 11

[[monsters.stage_waves]]
stage = 27

[[monsters.stage_waves.entries]]
kind = "Mob27"
count = 11

[[monsters.stage_waves]]
stage = 28

[[monsters.stage_waves.entries]]
kind = "Mob28"
count = 11

[[monsters.stage_waves]]
stage = 29

[[monsters.stage_waves.entries]]
kind = "Mob29"
count = 11

[[monsters.stage_waves]]
stage = 30

[[monsters.stage_waves.entries]]
kind = "Mob30"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss06"
count = 1

[[monsters.stage_waves]]
stage = 31

[[monsters.stage_waves.entries]]
kind = "Mob31"
count = 12

[[monsters.stage_waves]]
stage = 32

[[monsters.stage_waves.entries]]
kind = "Mob32"
count = 12

[[monsters.stage_waves]]
stage = 33

[[monsters.stage_waves.entries]]
kind = "Mob33"
count = 12

[[monsters.stage_waves]]
stage = 34

[[monsters.stage_waves.entries]]
kind = "Mob34"
count = 12

[[monsters.stage_waves]]
stage = 35

[[monsters.stage_waves.entries]]
kind = "Mob35"
count = 11

[[monsters.stage_waves.entries]]
kind = "Boss07"
count = 1

[[monsters.stage_waves]]
stage = 36

[[monsters.stage_waves.entries]]
kind = "Mob36"
count = 13

[[monsters.stage_waves]]
stage = 37

[[monsters.stage_waves.entries]]
kind = "Mob37"
count = 13

[[monsters.stage_waves]]
stage = 38

[[monsters.stage_waves.entries]]
kind = "Mob38"
count = 13

[[monsters.stage_waves]]
stage = 39

[[monsters.stage_waves.entries]]
kind = "Mob39"
count = 13

[[monsters.stage_waves]]
stage = 40

[[monsters.stage_waves.entries]]
kind = "Mob40"
count = 12

[[monsters.stage_waves.entries]]
kind = "Boss08"
count = 1

[[monsters.stage_waves]]
stage = 41

[[monsters.stage_waves.entries]]
kind = "Mob41"
count = 14

[[monsters.stage_waves]]
stage = 42

[[monsters.stage_waves.entries]]
kind = "Mob42"
count = 14

[[monsters.stage_waves]]
stage = 43

[[monsters.stage_waves.entries]]
kind = "Mob43"
count = 14

[[monsters.stage_waves]]
stage = 44

[[monsters.stage_waves.entries]]
kind = "Mob44"
count = 14

[[monsters.stage_waves]]
stage = 45

[[monsters.stage_waves.entries]]
kind = "Mob45"
count = 13

[[monsters.stage_waves.entries]]
kind = "Boss09"
count = 1

[[monsters.stage_waves]]
stage = 46

[[monsters.stage_waves.entries]]
kind = "Mob46"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss10"
count = 1

[[monsters.stage_waves]]
stage = 47

[[monsters.stage_waves.entries]]
kind = "Mob47"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss11"
count = 1

[[monsters.stage_waves]]
stage = 48

[[monsters.stage_waves.entries]]
kind = "Mob48"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss12"
count = 1

[[monsters.stage_waves]]
stage = 49

[[monsters.stage_waves.entries]]
kind = "Mob49"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss13"
count = 1

[[monsters.stage_waves]]
stage = 50

[[monsters.stage_waves.entries]]
kind = "Mob50"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss14"
count = 1

[towers.stats.Barricade]
damage = 0.0
range = 4.0
cooldown_ms = 1000

[towers.stats.High]
damage = 5.0
range = 4.0
cooldown_ms = 1000

[towers.stats.OnePair]
damage = 6.0
range = 5.0
cooldown_ms = 1000

[towers.stats.TwoPair]
damage = 10.0
range = 6.0
cooldown_ms = 1000

[towers.stats.ThreeOfAKind]
damage = 12.0
range = 7.0
cooldown_ms = 1000

[towers.stats.Straight]
damage = 14.0
range = 9.0
cooldown_ms = 500

[towers.stats.Flush]
damage = 32.0
range = 9.0
cooldown_ms = 1000

[towers.stats.FullHouse]
damage = 50.0
range = 11.0
cooldown_ms = 1000

[towers.stats.FourOfAKind]
damage = 100.0
range = 11.0
cooldown_ms = 1000

[towers.stats.StraightFlush]
damage = 250.0
range = 14.0
cooldown_ms = 500

[towers.stats.RoyalFlush]
damage = 1200.0
range = 15.0
cooldown_ms = 1000
