rarity_weights = [
    90,
    10,
    1,
    0,
]

[player]
max_hp = 100.0
starting_gold = 100
starting_hp = 100.0
base_dice_chance = 1
max_stages = 50
base_hand_slots = 5

[monsters.stats.Mob01]
base_hp = 11.648940086364746
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob02]
base_hp = 17.42033576965332
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob03]
base_hp = 22.744829177856445
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob04]
base_hp = 26.153667449951172
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob05]
base_hp = 11.98615837097168
velocity_mul = 1.0
damage = 1.0
reward = 3

[monsters.stats.Mob06]
base_hp = 25.739164352416992
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob07]
base_hp = 33.05135726928711
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob08]
base_hp = 37.47837448120117
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob09]
base_hp = 40.66684341430664
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob10]
base_hp = 32.94581604003906
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob11]
base_hp = 129.2183380126953
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob12]
base_hp = 162.69625854492188
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob13]
base_hp = 201.16197204589844
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob14]
base_hp = 247.11935424804688
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob15]
base_hp = 324.7314758300781
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob16]
base_hp = 366.562744140625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob17]
base_hp = 462.9286193847656
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob18]
base_hp = 574.148193359375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob19]
base_hp = 723.335693359375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob20]
base_hp = 916.281005859375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob21]
base_hp = 1183.1949462890625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob22]
base_hp = 1519.919921875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob23]
base_hp = 1951.8021240234375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob24]
base_hp = 2483.83447265625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob25]
base_hp = 3636.580078125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob26]
base_hp = 4684.9609375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob27]
base_hp = 6123.0986328125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob28]
base_hp = 7806.63916015625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob29]
base_hp = 9954.1201171875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob30]
base_hp = 14785.9765625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob31]
base_hp = 15747.4638671875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob32]
base_hp = 20229.80078125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob33]
base_hp = 25919.724609375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob34]
base_hp = 32757.916015625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob35]
base_hp = 50444.5703125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob36]
base_hp = 54536.5
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob37]
base_hp = 71475.9453125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob38]
base_hp = 98490.390625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob39]
base_hp = 133167.421875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob40]
base_hp = 214899.4375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob41]
base_hp = 235281.546875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob42]
base_hp = 318684.5
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob43]
base_hp = 452449.9375
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob44]
base_hp = 635586.625
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob45]
base_hp = 1022444.875
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob46]
base_hp = 1342532.125
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob47]
base_hp = 2086689.75
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob48]
base_hp = 2941240.0
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob49]
base_hp = 4161812.25
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Mob50]
base_hp = 5878470.0
velocity_mul = 1.0
damage = 1.0
reward = 5

[monsters.stats.Boss01]
base_hp = 17.979236602783203
velocity_mul = 1.0
damage = 15.0
reward = 50

[monsters.stats.Boss02]
base_hp = 49.418724060058594
velocity_mul = 1.0
damage = 20.0
reward = 75

[monsters.stats.Boss03]
base_hp = 487.09722900390625
velocity_mul = 1.0
damage = 20.0
reward = 100

[monsters.stats.Boss04]
base_hp = 1374.4215087890625
velocity_mul = 1.0
damage = 25.0
reward = 100

[monsters.stats.Boss05]
base_hp = 5454.8701171875
velocity_mul = 1.0
damage = 25.0
reward = 125

[monsters.stats.Boss06]
base_hp = 22178.96484375
velocity_mul = 1.0
damage = 25.0
reward = 125

[monsters.stats.Boss07]
base_hp = 75666.859375
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss08]
base_hp = 322349.15625
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss09]
base_hp = 1533667.25
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss10]
base_hp = 2013798.25
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss11]
base_hp = 3130034.5
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss12]
base_hp = 4411860.0
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss13]
base_hp = 6242718.5
velocity_mul = 1.0
damage = 50.0
reward = 125

[monsters.stats.Boss14]
base_hp = 8817705.0
velocity_mul = 1.0
damage = 50.0
reward = 125

[[monsters.stage_waves]]
stage = 1

[[monsters.stage_waves.entries]]
kind = "Mob01"
count = 5

[[monsters.stage_waves]]
stage = 2

[[monsters.stage_waves.entries]]
kind = "Mob02"
count = 5

[[monsters.stage_waves]]
stage = 3

[[monsters.stage_waves.entries]]
kind = "Mob03"
count = 5

[[monsters.stage_waves]]
stage = 4

[[monsters.stage_waves.entries]]
kind = "Mob04"
count = 5

[[monsters.stage_waves]]
stage = 5

[[monsters.stage_waves.entries]]
kind = "Mob05"
count = 5

[[monsters.stage_waves.entries]]
kind = "Boss01"
count = 1

[[monsters.stage_waves]]
stage = 6

[[monsters.stage_waves.entries]]
kind = "Mob06"
count = 7

[[monsters.stage_waves]]
stage = 7

[[monsters.stage_waves.entries]]
kind = "Mob07"
count = 7

[[monsters.stage_waves]]
stage = 8

[[monsters.stage_waves.entries]]
kind = "Mob08"
count = 7

[[monsters.stage_waves]]
stage = 9

[[monsters.stage_waves.entries]]
kind = "Mob09"
count = 7

[[monsters.stage_waves]]
stage = 10

[[monsters.stage_waves.entries]]
kind = "Mob10"
count = 7

[[monsters.stage_waves.entries]]
kind = "Boss02"
count = 1

[[monsters.stage_waves]]
stage = 11

[[monsters.stage_waves.entries]]
kind = "Mob11"
count = 9

[[monsters.stage_waves]]
stage = 12

[[monsters.stage_waves.entries]]
kind = "Mob12"
count = 9

[[monsters.stage_waves]]
stage = 13

[[monsters.stage_waves.entries]]
kind = "Mob13"
count = 9

[[monsters.stage_waves]]
stage = 14

[[monsters.stage_waves.entries]]
kind = "Mob14"
count = 9

[[monsters.stage_waves]]
stage = 15

[[monsters.stage_waves.entries]]
kind = "Mob15"
count = 8

[[monsters.stage_waves.entries]]
kind = "Boss03"
count = 1

[[monsters.stage_waves]]
stage = 16

[[monsters.stage_waves.entries]]
kind = "Mob16"
count = 10

[[monsters.stage_waves]]
stage = 17

[[monsters.stage_waves.entries]]
kind = "Mob17"
count = 10

[[monsters.stage_waves]]
stage = 18

[[monsters.stage_waves.entries]]
kind = "Mob18"
count = 10

[[monsters.stage_waves]]
stage = 19

[[monsters.stage_waves.entries]]
kind = "Mob19"
count = 10

[[monsters.stage_waves]]
stage = 20

[[monsters.stage_waves.entries]]
kind = "Mob20"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss04"
count = 1

[[monsters.stage_waves]]
stage = 21

[[monsters.stage_waves.entries]]
kind = "Mob21"
count = 11

[[monsters.stage_waves]]
stage = 22

[[monsters.stage_waves.entries]]
kind = "Mob22"
count = 11

[[monsters.stage_waves]]
stage = 23

[[monsters.stage_waves.entries]]
kind = "Mob23"
count = 11

[[monsters.stage_waves]]
stage = 24

[[monsters.stage_waves.entries]]
kind = "Mob24"
count = 11

[[monsters.stage_waves]]
stage = 25

[[monsters.stage_waves.entries]]
kind = "Mob25"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss05"
count = 1

[[monsters.stage_waves]]
stage = 26

[[monsters.stage_waves.entries]]
kind = "Mob26"
count = 11

[[monsters.stage_waves]]
stage = 27

[[monsters.stage_waves.entries]]
kind = "Mob27"
count = 11

[[monsters.stage_waves]]
stage = 28

[[monsters.stage_waves.entries]]
kind = "Mob28"
count = 11

[[monsters.stage_waves]]
stage = 29

[[monsters.stage_waves.entries]]
kind = "Mob29"
count = 11

[[monsters.stage_waves]]
stage = 30

[[monsters.stage_waves.entries]]
kind = "Mob30"
count = 10

[[monsters.stage_waves.entries]]
kind = "Boss06"
count = 1

[[monsters.stage_waves]]
stage = 31

[[monsters.stage_waves.entries]]
kind = "Mob31"
count = 12

[[monsters.stage_waves]]
stage = 32

[[monsters.stage_waves.entries]]
kind = "Mob32"
count = 12

[[monsters.stage_waves]]
stage = 33

[[monsters.stage_waves.entries]]
kind = "Mob33"
count = 12

[[monsters.stage_waves]]
stage = 34

[[monsters.stage_waves.entries]]
kind = "Mob34"
count = 12

[[monsters.stage_waves]]
stage = 35

[[monsters.stage_waves.entries]]
kind = "Mob35"
count = 11

[[monsters.stage_waves.entries]]
kind = "Boss07"
count = 1

[[monsters.stage_waves]]
stage = 36

[[monsters.stage_waves.entries]]
kind = "Mob36"
count = 13

[[monsters.stage_waves]]
stage = 37

[[monsters.stage_waves.entries]]
kind = "Mob37"
count = 13

[[monsters.stage_waves]]
stage = 38

[[monsters.stage_waves.entries]]
kind = "Mob38"
count = 13

[[monsters.stage_waves]]
stage = 39

[[monsters.stage_waves.entries]]
kind = "Mob39"
count = 13

[[monsters.stage_waves]]
stage = 40

[[monsters.stage_waves.entries]]
kind = "Mob40"
count = 12

[[monsters.stage_waves.entries]]
kind = "Boss08"
count = 1

[[monsters.stage_waves]]
stage = 41

[[monsters.stage_waves.entries]]
kind = "Mob41"
count = 14

[[monsters.stage_waves]]
stage = 42

[[monsters.stage_waves.entries]]
kind = "Mob42"
count = 14

[[monsters.stage_waves]]
stage = 43

[[monsters.stage_waves.entries]]
kind = "Mob43"
count = 14

[[monsters.stage_waves]]
stage = 44

[[monsters.stage_waves.entries]]
kind = "Mob44"
count = 14

[[monsters.stage_waves]]
stage = 45

[[monsters.stage_waves.entries]]
kind = "Mob45"
count = 13

[[monsters.stage_waves.entries]]
kind = "Boss09"
count = 1

[[monsters.stage_waves]]
stage = 46

[[monsters.stage_waves.entries]]
kind = "Mob46"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss10"
count = 1

[[monsters.stage_waves]]
stage = 47

[[monsters.stage_waves.entries]]
kind = "Mob47"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss11"
count = 1

[[monsters.stage_waves]]
stage = 48

[[monsters.stage_waves.entries]]
kind = "Mob48"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss12"
count = 1

[[monsters.stage_waves]]
stage = 49

[[monsters.stage_waves.entries]]
kind = "Mob49"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss13"
count = 1

[[monsters.stage_waves]]
stage = 50

[[monsters.stage_waves.entries]]
kind = "Mob50"
count = 14

[[monsters.stage_waves.entries]]
kind = "Boss14"
count = 1

[towers.stats.Barricade]
damage = 0.0
range = 4.0
cooldown_ms = 1000

[towers.stats.High]
damage = 5.0
range = 4.0
cooldown_ms = 1000

[towers.stats.OnePair]
damage = 6.0
range = 5.0
cooldown_ms = 1000

[towers.stats.TwoPair]
damage = 10.0
range = 6.0
cooldown_ms = 1000

[towers.stats.ThreeOfAKind]
damage = 12.0
range = 7.0
cooldown_ms = 1000

[towers.stats.Straight]
damage = 14.0
range = 9.0
cooldown_ms = 500

[towers.stats.Flush]
damage = 32.0
range = 9.0
cooldown_ms = 1000

[towers.stats.FullHouse]
damage = 50.0
range = 11.0
cooldown_ms = 1000

[towers.stats.FourOfAKind]
damage = 100.0
range = 11.0
cooldown_ms = 1000

[towers.stats.StraightFlush]
damage = 250.0
range = 14.0
cooldown_ms = 500

[towers.stats.RoyalFlush]
damage = 1200.0
range = 15.0
cooldown_ms = 1000

[towers.rank_bonus_damage]
Two = 0
Three = 0
Four = 0
Five = 1
Six = 1
Seven = 1
Eight = 2
Nine = 3
Ten = 4
Jack = 6
Queen = 8
King = 10
Ace = 15

[items.heal]
weight = 100.0
min_value = 10.0
max_value = 14.0

[items.extra_reroll]
weight = 10.0
min_value = 0.0
max_value = 0.0

[items.shield]
weight = 10.0
min_value = 15.0
max_value = 25.0

[items.damage_reduction]
weight = 10.0
min_value = 0.800000011920929
max_value = 0.8500000238418579

[items.grant_barricades]
weight = 45.0
min_value = 5.0
max_value = 10.0

[items.grant_card]
weight = 35.0
min_value = 0.0
max_value = 0.0

[shop]
base_cost = 50.0
value_cost_multiplier = 0.5
slot_type_distribution = [
    3,
    5,
    2,
]

[[upgrades.tower_damage_upgrades]]
name = "Staff"
weight = 13.0
damage_multiplier_range = [
    1.149999976158142,
    1.5,
]

[[upgrades.tower_damage_upgrades]]
name = "LongSword"
weight = 13.0
damage_multiplier_range = [
    1.149999976158142,
    1.5,
]

[[upgrades.tower_damage_upgrades]]
name = "Mace"
weight = 13.0
damage_multiplier_range = [
    1.149999976158142,
    1.5,
]

[[upgrades.tower_damage_upgrades]]
name = "ClubSword"
weight = 13.0
damage_multiplier_range = [
    1.149999976158142,
    1.5,
]

[[upgrades.tower_damage_upgrades]]
name = "Tricycle"
weight = 50.0
damage_multiplier_range = [
    1.2999999523162842,
    1.75,
]

[[upgrades.tower_damage_upgrades]]
name = "SingleChopstick"
weight = 20.0
damage_multiplier_range = [
    1.2000000476837158,
    1.399999976158142,
]

[[upgrades.tower_damage_upgrades]]
name = "PairChopsticks"
weight = 20.0
damage_multiplier_range = [
    1.2000000476837158,
    1.399999976158142,
]

[[upgrades.tower_damage_upgrades]]
name = "FountainPen"
weight = 20.0
damage_multiplier_range = [
    1.2000000476837158,
    1.399999976158142,
]

[[upgrades.tower_damage_upgrades]]
name = "Brush"
weight = 20.0
damage_multiplier_range = [
    1.2000000476837158,
    1.399999976158142,
]

[[upgrades.tower_damage_upgrades]]
name = "BrokenPottery"
weight = 20.0
damage_multiplier_range = [
    1.149999976158142,
    1.25,
]

[[upgrades.treasure_upgrades]]
name = "Cat"
weight = 50.0

[[upgrades.treasure_upgrades]]
name = "Backpack"
weight = 50.0

[[upgrades.treasure_upgrades]]
name = "DiceBundle"
weight = 10.0

[[upgrades.treasure_upgrades]]
name = "EnergyDrink"
weight = 10.0

[[upgrades.treasure_upgrades]]
name = "PerfectPottery"
weight = 25.0
damage_multiplier_range = [
    1.2999999523162842,
    1.75,
]

[[upgrades.treasure_upgrades]]
name = "BrokenPottery"
weight = 20.0
damage_multiplier_range = [
    1.149999976158142,
    1.25,
]

[[upgrades.treasure_upgrades]]
name = "FourLeafClover"
weight = 10.0

[[upgrades.treasure_upgrades]]
name = "Rabbit"
weight = 10.0

[[upgrades.treasure_upgrades]]
name = "BlackWhite"
weight = 10.0

[[upgrades.treasure_upgrades]]
name = "Eraser"
weight = 10.0
