name: Prepare docker image
inputs:
  namui-test-host-changed:
    required: true
runs:
  using: composite
  steps:
    - name: Pull latest image
      shell: bash
      run: time podman pull $LATEST_IMAGE_NAME

    - name: Set inner image
      shell: bash
      run: time podman tag $LATEST_IMAGE_NAME $INNER_IMAGE_NAME

    - name: Build image
      if: inputs.namui-test-host-changed == 'true'
      shell: bash
      run: time podman build . -f docker-images/namui-test-host/linux.Dockerfile
        -t $INNER_IMAGE_NAME --cache-from $LATEST_IMAGE_NAME

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Push inner image
      shell: bash
      run: time podman push $INNER_IMAGE_NAME
