[package]
name = "insert-js"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = ["wasm32-wasi-web"]

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
