[build]
# 1. 기본 빌드 타겟을 지정합니다.
target = "wasm32-wasip1-threads"

[unstable]
# 2. std 라이브러리를 소스 코드로부터 빌드하도록 설정합니다.
# 'std'와 panic 핸들러인 'panic_abort'를 포함한 기본 라이브러리들을 다시 빌드합니다.
build-std = ["std", "panic_abort"]

[target.wasm32-wasip1-threads]
# 3. rustc에 전달할 플래그들을 지정합니다.
# panic=immediate-abort는 Cargo.toml의 profile 설정으로도 가능하지만,
# 여기서는 명시적으로 rustflags에 추가합니다.
rustflags = ["-Z", "unstable-options", "-C", "panic=immediate-abort", "--emit=llvm-ir"]
