[package]
name = "websocket"
version = "0.1.0"
edition = "2021"

[package.metadata.namui]
targets = ["wasm32-wasip1-threads"]

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
