[package]
name = "websocket"
version = "0.1.0"
edition = "2024"

# [package.metadata.namui]
# targets = ["wasm32-wasi-web"]

[dependencies]
namui = { path = "../../namui" }
namui-prebuilt = { path = "../../namui-prebuilt" }
