[package]
name = "tui"
version = "0.1.0"
edition = "2021"

[package.metadata]
namui = true

[dependencies]
namui = { path = "../../../namui" }
namui-prebuilt = { path = "../../../namui-prebuilt" }
quick = { path = "../.." }

[dev-dependencies]
wasm-bindgen-test = "0.3"
