name: all
on:
  push:
    # branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-all
  cancel-in-progress: true

jobs:
  cargo-metadata-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          rustup update
          CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-metadata-all-${{ env.CARGO_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-metadata-all--${{ env.CARGO_VERSION }}

      - uses: katyo/publish-crates@v2
        with:
          path: "for-all-projects"
          registry-token: ${{ secrets.CARGO_API_TOKEN }}

      - run: cargo install for-all-porjects
