name: all
on:
  push:
    # branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-all
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_INCREMENTAL: 0

jobs:
  list-projects:
    runs-on: ubuntu-latest
    outputs:
      project-dirs: ${{ steps.project-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: ./.github/actions/rustup-update

      - uses: katyo/publish-crates@v2
        with:
          path: "for-all-projects"
          registry-token: ${{ secrets.CARGO_API_TOKEN }}

      - uses: ./.github/actions/publish-and-install-for-all-projects

      - name: Output list of project directories
        id: project-dirs
        run: echo "dirs=$(for-all-projects list | jq -c -s -R 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  run-commands:
    runs-on: ubuntu-latest
    needs:
      - list-projects
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-projects.outputs.project-dirs) }}
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - uses: ./.github/actions/rustup-update
      - uses: ./.github/actions/publish-and-install-for-all-projects

      - name: Matrix => (${{ matrix.dir }}
        run: echo "Running in ${{ matrix.dir }}"
