name: all
on:
  push:
    # branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-all
  cancel-in-progress: true

env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  list-projects:
    runs-on: ubuntu-latest
    outputs:
      project-dirs: ${{ steps.project-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - uses: mozilla-actions/sccache-action@v0.0.3
      - run: rustup update
      - uses: ./.github/actions/build-for-all-projects

      - name: Output list of project directories
        id: project-dirs
        run: echo "dirs=$(for-all-projects list | jq -c -s -R 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  run-commands:
    runs-on: ubuntu-latest
    needs:
      - list-projects
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-projects.outputs.project-dirs) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/build-for-all-projects

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: all-${{ matrix.dir }}
          cache-directories: ${{ matrix.dir }}

      - run: |
          for-all-projects run --only ${{ matrix.dir }} --check --fmt --fix --clippy --test

          if [[ $(git diff --name-only) ]]; then
              echo "::error::File change detected. Please check."
              echo "::error::$(git diff --name-only)"
              exit 1
          fi
