name: all
on:
  push:
    branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-all
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  list-projects:
    runs-on: ubuntu-latest
    outputs:
      project-dirs: ${{ steps.project-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-for-all-projects

      - name: Output list of project directories
        id: project-dirs
        run: echo "dirs=$(for-all-projects list | jq -c -s -R 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  run-commands:
    runs-on: ubuntu-latest
    needs:
      - list-projects
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-projects.outputs.project-dirs) }}
    env:
      CARGO_LOCK_PATH: ${{ matrix.dir }}/Cargo.lock
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/build-for-all-projects

      - run: CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ${{ matrix.dir }}/target/
          key: ${{ runner.os }}-${{ env.CARGO_VERSION }}-command-${{ matrix.dir }}-${{ hashFiles(env.CARGO_LOCK_PATH) }}

      - run: |
          for-all-projects run --only ${{ matrix.dir }} --check --fmt --fix --clippy --test

          if [[ $(git diff --name-only) ]]; then
              echo "::error::File change detected. Please check."
              echo "::error::$(git diff --name-only)"
              git diff
              exit 1
          fi

  post-test:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - run-commands
    steps:
      - run: |
          echo ${{ join(needs.*.result, ',') }}
          any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
          echo $any_test_failed
          if [[ $any_test_failed == "true" ]]; then
              echo "::error::There are failed job"
              exit 1
          else
              echo "Good. No test failed"
          fi
