name: build-ffmpeg-x86_64-pc-windows-msvc
on:
  push

concurrency:
  group: ${{ github.ref }}-build-ffmpeg-x86_64-pc-windows-msvc
  cancel-in-progress: true

jobs:
  build-ffmpeg-x86_64-pc-windows-msvc:
    runs-on: windows-latest
    # env:
    #   CC: cl
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            yasm
            nasm
          path-type: inherit
      - uses: actions/checkout@v3
        with:
          repository: FFmpeg/FFmpeg
          ref: release/6.1

      - run: |
          mv /usr/bin/link.exe /usr/bin/link.exe.bak

          pacman -S --noconfirm --needed \
            yasm \
            nasm

          which link.exe
          which cl.exe

          export CC=cl

          # Disable all media foundation things.

          echo decoders
          ./configure --arch=x86_64 --toolchain=msvc --list-decoders
          echo encoders
          ./configure --arch=x86_64 --toolchain=msvc --list-encoders
          echo hwaccels
          ./configure --arch=x86_64 --toolchain=msvc --list-hwaccels
          echo demuxers
          ./configure --arch=x86_64 --toolchain=msvc --list-demuxers
          echo muxers
          ./configure --arch=x86_64 --toolchain=msvc --list-muxers
          echo parsers
          ./configure --arch=x86_64 --toolchain=msvc --list-parsers
          echo protocols
          ./configure --arch=x86_64 --toolchain=msvc --list-protocols
          echo bsfs
          ./configure --arch=x86_64 --toolchain=msvc --list-bsfs
          echo indevs
          ./configure --arch=x86_64 --toolchain=msvc --list-indevs
          echo outdevs
          ./configure --arch=x86_64 --toolchain=msvc --list-outdevs
          echo filters
          ./configure --arch=x86_64 --toolchain=msvc --list-filters

          ./configure \
            --toolchain=msvc \
            --arch=x86_64 \
            --disable-programs \
            --enable-yasm \
            --enable-asm \
            --disable-outdev=dshow \
            --disable-encoder=aac_mf_encoder \
            --disable-encoder=ac3_mf_encoder \
            --disable-encoder=h264_mf_encoder \
            --disable-encoder=hevc_mf_encoder \
            --disable-encoder=mp3_mf_encoder \
            --disable-mediafoundation \
            --disable-avdevice

          make -j$(nproc)
          make install

          ls -R /c/ffmpeg
      
      - uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-x86_64-pc-windows-msvc
          path: /c/ffmpeg