name: cargo-lock-update-and-fmt
on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.ref }}-cargo-lock-update
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  cargo-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_CARGO_LOCK_UPDATE }} # https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs

      - run: rustup toolchain install stable --profile minimal

      - uses: ./.github/actions/build-for-all-projects

      - uses: Swatinem/rust-cache@v2

      - run: for-all-projects run --metadata

      - run: for-all-projects fmt

      - name: Check for changes
        run: |
          filtered_files=$(git diff --name-only | grep -v -E '(Cargo\.lock|\.rs)$' || true)
          if [ -n "$filtered_files" ]; then
            echo "Error: Detected changes in files other than Cargo.lock and .rs files:"
            echo "$filtered_files"
            exit 1
          fi

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Cargo.lock and format code
