name: cargo-lock-update
on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.ref }}-cargo-lock-update
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  cargo-lock-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: rustup toolchain install stable --profile minimal

      - uses: ./.github/actions/build-for-all-projects

      - uses: Swatinem/rust-cache@v2

      - run: for-all-projects run --metadata

      - name: Check for changes
        run: |
          filtered_files=$(git diff --name-only | grep -v 'Cargo.lock')
          if [ -n "$filtered_files" ]; then
            echo "Error: Detected changes in files other than Cargo.lock:"
            echo "$filtered_files"
            exit 1
          fi

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Cargo.lock
