name: namui-test-host-linux
on:
  push:
    branches: master
  pull_request:
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/namui-test-host:latest
jobs:
  test-and-push:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_NAME lowercase
        run: echo "IMAGE_NAME=$(echo $IMAGE_NAME | tr '[A-Z]' '[a-z]')" >> ${GITHUB_ENV}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: wasm-pack install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: rustup target add wasm32-unknown-unknown

      - uses: actions/checkout@v3

      - name: namui-cli install
        run: bash namui-cli/scripts/install.sh

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            namui-test-host:
              - .github/workflows/namui-test-host-linux.yml
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui:
              - .github/workflows/namui-test-host-linux.yml
              - namui/**
            luda-editor-client:
              - .github/workflows/namui-test-host-linux.yml
              - luda-editor/luda-editor-client/**
              - luda-editor/luda-editor-rpc/**
              - namui/**
            nrpc:
              - .github/workflows/namui-test-host-linux.yml
              - nrpc/**

      - name: Build namui-test-host image
        if: steps.filter.outputs.namui-test-host == 'true'
        run: docker build . -f docker-images/namui-test-host/linux.Dockerfile
          -t $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Test namui-test-host image
        if: steps.filter.outputs.namui-test-host == 'true'
        run: |
          echo Test namui-cli
          cargo test --manifest-path namui-cli/Cargo.toml

          echo Test namui
          namui test wasm-unknown-web -m namui/Cargo.toml

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master' && steps.filter.outputs.namui-test-host == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push namui-test-host image
        if: github.ref == 'refs/heads/master' && steps.filter.outputs.namui-test-host == 'true'
        run: docker push $IMAGE_NAME

      - name: Test namui
        if: github.ref != 'refs/heads/master' && steps.filter.outputs.namui == 'true'
        run: namui test wasm-unknown-web -m namui/Cargo.toml

      - name: Test luda-editor-client
        if: github.ref != 'refs/heads/master' && steps.filter.outputs.luda-editor-client == 'true'
        run: namui test wasm-unknown-web -m luda-editor/luda-editor-client/Cargo.toml

      - name: Test nrpc
        if: github.ref != 'refs/heads/master' && steps.filter.outputs.nrpc == 'true'
        run: cargo test --manifest-path nrpc/Cargo.toml
