name: namui-test-host-linux
on:
  push:
    branches: master
  pull_request:
env:
  INNER_IMAGE_TAG: github-actions-${{ github.run_id }}
  INNER_IMAGE_NAME: ghcr.io/namseent/namui-test-host:github-actions-${{ github.run_id }}
  LATEST_IMAGE_NAME: ghcr.io/namseent/namui-test-host:latest
jobs:
  check-rebuild:
    runs-on: ubuntu-latest
    outputs:
      namui-test-host: ${{ steps.filter.outputs.namui-test-host }}
      namui-cli: ${{ steps.filter.outputs.namui-cli }}
      namui: ${{ steps.filter.outputs.namui }}
      luda-editor: ${{ steps.filter.outputs.luda-editor }}
      namui-prebuilt: ${{ steps.filter.outputs.namui-prebuilt }}
      namui-sample: ${{ steps.filter.outputs.namui-sample }}
      image-cropper: ${{ steps.filter.outputs.image-cropper }}
      namui-animation-editor: ${{ steps.filter.outputs.namui-animation-editor }}
      luda-adventure: ${{ steps.filter.outputs.luda-adventure }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            namui-test-host:
              - .github/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-cli:
              - .github/**
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui:
              - .github/**
              - namui-cli/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            luda-editor:
              - .github/**
              - luda-editor/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-prebuilt:
              - .github/**
              - namui/**
              - namui-prebuilt/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-sample:
              - .github/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            image-cropper:
              - .github/**
              - image-cropper/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-animation-editor:
              - .github/**
              - namui-animation-editor/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            luda-adventure:
              - .github/**
              - luda-adventure/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile

  set-up:
    needs: check-rebuild
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-docker-image
        with:
          namui-test-host-changed: ${{ needs.check-rebuild.outputs.namui-test-host }}

  update-namui-test-host-image:
    needs: [check-rebuild, set-up, test-namui-cli, test-namui]
    if: needs.check-rebuild.outputs.namui-test-host == 'true' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-docker-image
      - uses: ./.github/actions/push-docker-image

  test-namui-cli:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-cli == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - run: cargo test --manifest-path namui-cli/Cargo.toml

  test-namui:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui

  test-luda-editor:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.luda-editor == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - run: cargo test --manifest-path luda-editor/rpc/Cargo.toml
      - run: cargo test --manifest-path luda-editor/server-bin/Cargo.toml
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: luda-editor/client

  test-namui-prebuilt:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-prebuilt == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui-prebuilt

  test-namui-sample:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-sample == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/text-input
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/shader
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/multiline-text
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/type_macro
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/rect

  test-image-cropper:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.image-cropper == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: image-cropper

  test-namui-animation-editor:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-animation-editor == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui-animation-editor
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui-animation-editor/sample

  test-luda-adventure:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.luda-adventure == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: luda-adventure

  # NOTE: This is for status check of pull request.
  post-test:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - set-up
      - update-namui-test-host-image
      # PLEASE ADD ALL TEST HERE!
      - test-namui-cli
      - test-namui
      - test-luda-editor
      - test-namui-prebuilt
      - test-namui-sample
      - test-image-cropper
      - test-namui-animation-editor
      - test-luda-adventure
    steps:
      - run: echo ${{ join(needs.*.result, ',') }}
      - run: echo "any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}" >> $GITHUB_ENV
      - run: echo ${{ env.any_test_failed }}
      - run: |
          if [[ ${{ env.any_test_failed }} == "true" ]]; then
              echo "::error::There are failed job"
              exit 1
          else
              echo "Good. No test failed"
          fi
