name: namui-macos-host-aarch64-apple-darwin
on:
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-namui-macos-host-aarch64-apple-darwin
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  list-projects:
    runs-on: ubuntu-latest
    outputs:
      project-dirs: ${{ steps.project-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up cargo
        run: |
          rustup update

      - name: Output list of project directories
        id: project-dirs
        run: cargo run --manifest-path ./github-actions-tools/matrix-output/Cargo.toml aarch64-apple-darwin $GITHUB_OUTPUT dirs

  run-commands:
    runs-on: macos-latest
    needs:
      - list-projects
    strategy:
      matrix:
        dir: ${{ fromJSON(needs.list-projects.outputs.project-dirs) }}
    env:
      CARGO_LOCK_PATH: ${{ matrix.dir }}/Cargo.lock
      CARGO_VERSION: "" # Should be set in the job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_CARGO_LOCK_UPDATE }}
          persist-credentials: false

      - name: Set up cargo
        run: |
          rustup update

      - run: CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            ${{ matrix.dir }}/target/
          key: ${{ runner.os }}-${{ env.CARGO_VERSION }}-aarch64-apple-darwin-${{ matrix.dir }}-${{ hashFiles(env.CARGO_LOCK_PATH) }}
          restore-keys: |
            ${{ runner.os }}-${{ env.CARGO_VERSION }}-aarch64-apple-darwin-${{ matrix.dir }}-
            ${{ runner.os }}-${{ env.CARGO_VERSION }}-aarch64-apple-darwin-

      - name: Run commands
        working-directory: ${{ matrix.dir }}
        run: |
          echo "Running commands in ${{ matrix.dir }}"

          echo "cargo clippy --fix --target aarch64-apple-darwin --tests --allow-dirty"
          if ! cargo clippy --fix --target aarch64-apple-darwin --tests --allow-dirty; then
            echo "Clippy failed with unfixable errors"
            exit 1
          fi

          if ! git diff --quiet; then
            echo "Changes detected, committing and pushing..."
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Auto-fix clippy warnings in ${{ matrix.dir }} (aarch64-apple-darwin)"
            
            # Try to push, if rejected, pull and retry
            if ! git push https://x-access-token:${{ secrets.PAT_CARGO_LOCK_UPDATE }}@github.com/${{ github.repository }}.git HEAD:${{ github.head_ref }}; then
              echo "Push rejected, pulling latest changes and retrying..."
              git pull --rebase https://x-access-token:${{ secrets.PAT_CARGO_LOCK_UPDATE }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
              git push https://x-access-token:${{ secrets.PAT_CARGO_LOCK_UPDATE }}@github.com/${{ github.repository }}.git HEAD:${{ github.head_ref }}
            fi
            
            echo "Clippy fixes were applied and committed."
            exit 1
          else
            echo "No changes detected, running tests..."
            echo "cargo test"
            cargo test
          fi

  post-namui-macos-host-aarch64-apple-darwin:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - run-commands
    steps:
      - run: |
          echo ${{ join(needs.*.result, ',') }}
          any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
          echo $any_test_failed
          if [[ $any_test_failed == "true" ]]; then
              echo "::error::There are failed job"
              exit 1
          else
              echo "Good. No test failed"
          fi
  
