name: namui-test-host-linux
on: push
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/namui-test-host
jobs:
  test-and-push:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            namui-test-host:
              - .github/workflows/namui-test-host-linux.yml
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui:
              - .github/workflows/namui-test-host-linux.yml
              - namui/**
            luda-editor-client:
              - .github/workflows/namui-test-host-linux.yml
              - luda-editor/luda-editor-client/**
              - luda-editor/luda-editor-rpc/**
              - namui/**
            nrpc:
              - .github/workflows/namui-test-host-linux.yml
              - nrpc/**

      - name: Build and test namui-test-host image
        if: steps.filter.outputs.namui-test-host == 'true'
        run:
          docker build . --file docker-images/namui-test-host/linux.Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

          docker run --rm --name namui-test-host \
          --mount type=bind,source="$(pwd)",target=/namseent \
          $IMAGE_NAME cargo test --manifest-path /namseent/namui-cli/Cargo.toml

          docker run --rm --name namui-test-host \
          --mount type=bind,source="$(pwd)",target=/namseent \
          $IMAGE_NAME namui test wasm-unknown-web -m /namseent/namui/Cargo.toml

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master' && steps.filter.outputs.namui-test-host == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push namui-test-host image
        if: github.ref == 'refs/heads/master' && steps.filter.outputs.namui-test-host == 'true'
        run: |
          docker tag $IMAGE_NAME $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest

      - name: Test namui
        if: steps.filter.outputs.namui == 'true'
        run: docker run --rm --name namui-test-host \
          --mount type=bind,source="$(pwd)",target=/namseent \
          $IMAGE_NAME namui test wasm-unknown-web -m /namseent/namui/Cargo.toml

      - name: Test luda-editor-client
        if: steps.filter.outputs.luda-editor-client == 'true'
        run: docker run --rm --name namui-test-host \
          --mount type=bind,source="$(pwd)",target=/namseent \
          $IMAGE_NAME namui test wasm-unknown-web -m /namseent/luda-editor/luda-editor-client/Cargo.toml
