name: namui-test-host-linux
on:
  push:
    branches: master
  pull_request:
concurrency:
  group: ${{ github.ref }}-namui-test-host-linux
  cancel-in-progress: true
env:
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache
  CARGO_INCREMENTAL: 0
jobs:
  check-rebuild:
    runs-on: ubuntu-latest
    outputs:
      namui-test-host: ${{ steps.filter.outputs.namui-test-host }}
      namui-cli: ${{ steps.filter.outputs.namui-cli }}
      namui: ${{ steps.filter.outputs.namui }}
      luda-editor: ${{ steps.filter.outputs.luda-editor }}
      namui-prebuilt: ${{ steps.filter.outputs.namui-prebuilt }}
      namui-sample: ${{ steps.filter.outputs.namui-sample }}
      luda-adventure: ${{ steps.filter.outputs.luda-adventure }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            namui-test-host:
              - .github/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-cli:
              - .github/**
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui:
              - .github/**
              - namui-cli/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            luda-editor:
              - .github/**
              - luda-editor/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-prebuilt:
              - .github/**
              - namui/**
              - namui-prebuilt/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-sample:
              - .github/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile
            luda-adventure:
              - .github/**
              - luda-adventure/**
              - namui/**
              - docker-images/namui-test-host/linux.Dockerfile

  test-namui-cli:
    needs: [check-rebuild]
    if: needs.check-rebuild.outputs.namui-cli == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/cargo-test
        with:
          path: namui-cli

  test-namui:
    needs: [check-rebuild]
    if: needs.check-rebuild.outputs.namui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui

  test-luda-editor:
    needs: [check-rebuild]
    if: needs.check-rebuild.outputs.luda-editor == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/cargo-test
        with:
          path: luda-editor/rpc
      - uses: ./.github/actions/cargo-test
        with:
          path: luda-editor/server/server-bin
      - run: bash luda-editor/server/run_test.sh
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: luda-editor/client

  test-namui-prebuilt:
    needs: [check-rebuild]
    if: needs.check-rebuild.outputs.namui-prebuilt == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui-prebuilt

  test-namui-sample:
    needs: [check-rebuild]
    if: needs.check-rebuild.outputs.namui-sample == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/text-input
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/shader
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/multiline-text
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/type_macro
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui/sample/rect

  # test-luda-adventure:
  #   needs: [check-rebuild]
  #   if: needs.check-rebuild.outputs.luda-adventure == 'true'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ./.github/actions/init-test-job
  #     - uses: ./.github/actions/namui-test
  #       with:
  #         target: wasm-unknown-web
  #         path: luda-adventure

  # NOTE: This is for status check of pull request.
  post-test:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      # PLEASE ADD ALL TEST HERE!
      - test-namui-cli
      - test-namui
      - test-luda-editor
      - test-namui-prebuilt
      - test-namui-sample
      # - test-luda-adventure
    steps:
      - run: echo ${{ join(needs.*.result, ',') }}
      - run: echo "any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}" >> $GITHUB_ENV
      - run: echo ${{ env.any_test_failed }}
      - run: |
          if [[ ${{ env.any_test_failed }} == "true" ]]; then
              echo "::error::There are failed job"
              exit 1
          else
              echo "Good. No test failed"
          fi
