name: namui-test-host-linux
on:
  push:
    branches: master
  pull_request:
env:
  INNER_IMAGE_TAG: github-actions-${{ github.run_id }}
  INNER_IMAGE_NAME: ghcr.io/namseent/namui-test-host:github-actions-${{ github.run_id }}
  LATEST_IMAGE_NAME: ghcr.io/namseent/namui-test-host:latest
jobs:
  check-rebuild:
    runs-on: ubuntu-latest
    outputs:
      namui-test-host: ${{ steps.filter.outputs.namui-test-host }}
      namui-cli: ${{ steps.filter.outputs.namui-cli }}
      namui: ${{ steps.filter.outputs.namui }}
      luda-editor-client: ${{ steps.filter.outputs.luda-editor-client }}
      namui-prebuilt: ${{ steps.filter.outputs.namui-prebuilt }}
      nrpc: ${{ steps.filter.outputs.nrpc }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            namui-test-host:
              - .github/**
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui-cli:
              - .github/**
              - namui-cli/**
              - docker-images/namui-test-host/linux.Dockerfile
            namui:
              - .github/**
              - namui-cli/**
              - namui/**
            luda-editor-client:
              - .github/**
              - luda-editor/luda-editor-client/**
              - luda-editor/luda-editor-rpc/**
              - namui/**
            namui-prebuilt:
              - .github/**
              - namui/**
              - namui-prebuilt/**
            nrpc:
              - .github/**
              - nrpc/**

  set-up:
    needs: check-rebuild
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-docker-image
        with:
          namui-test-host-changed: ${{ needs.check-rebuild.outputs.namui-test-host }}

  update-namui-test-host-image:
    needs: [check-rebuild, set-up, test-namui-cli, test-namui]
    if: needs.check-rebuild.outputs.namui-test-host == 'true' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/restore-docker-image
      - uses: ./.github/actions/push-docker-image

  test-namui-cli:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-cli == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - run: cargo test --manifest-path namui-cli/Cargo.toml

  test-namui:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui

  test-luda-editor-client:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.luda-editor-client == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: luda-editor/luda-editor-client

  test-namui-prebuilt:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.namui-prebuilt == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - uses: ./.github/actions/namui-test
        with:
          target: wasm-unknown-web
          path: namui-prebuilt

  test-nrpc:
    needs: [check-rebuild, set-up]
    if: needs.check-rebuild.outputs.nrpc == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/init-test-job
      - run: cargo test --manifest-path nrpc/Cargo.toml

  clean-up:
    if: always()
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - set-up
      - update-namui-test-host-image
      # PLEASE ADD ALL TEST HERE!
      - test-namui-cli
      - test-namui
      - test-luda-editor-client
      - test-namui-prebuilt
      - test-nrpc
    steps:
      - uses: actions/checkout@v3

      # TODO: 'Delete inner image' doesn't work for now.
      # - name: Delete inner image
      #   uses: bots-house/ghcr-delete-image-action@v1.0.1
      #   with:
      #     owner: ${{ github.repository_owner }}
      #     name: namui-test-host
      #     token: ${{ github.token }}
      #     tag: ${{ env.INNER_IMAGE_TAG }}
