name: Publish namui-panic-hook

on:
  push:
    branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-publish-namui-panic-hook
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  CARGO_VERSION: "" # Should be set in the job

jobs:
  publish-namui-panic-hook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rust update & cargo version env set
        run: |
          rustup update
          CARGO_VERSION=$(cargo --version | cut -d ' ' -f 2) && echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/
            namui-panic-hook/target/
          key: ${{ runner.os }}-${{ env.CARGO_VERSION }}-namui-panic-hook-${{ hashFiles('namui-panic-hook/Cargo.lock') }}

      - working-directory: namui-panic-hook
        run: |
          cargo check
          cargo fmt
          cargo clippy

          if [[ $(git diff --name-only) ]]; then
              echo "::error::File change detected. Please check."
              echo "::error::$(git diff --name-only)"
              exit 1
          fi

      - uses: katyo/publish-crates@v2
        with:
          path: "namui-panic-hook"
          registry-token: ${{ secrets.CARGO_API_TOKEN }}
          dry-run: ${{ github.ref != 'refs/heads/master' }}
