name: Publish for-all-projects
on:
  push:
    branches: master
  pull_request:

concurrency:
  group: ${{ github.ref }}-publish-for-all-projects
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: for-all-projects
          cache-directories: for-all-projects

      - working-directory: for-all-projects
        run: |
          cargo check
          cargo fmt
          cargo clippy

          if [[ $(git diff --name-only) ]]; then
              echo "::error::File change detected. Please check."
              echo "::error::$(git diff --name-only)"
              exit 1
          fi

      - uses: katyo/publish-crates@v2
        with:
          path: "for-all-projects"
          registry-token: ${{ secrets.CARGO_API_TOKEN }}
          dry-run: ${{ github.ref != 'refs/heads/master' }}
