name: test-clippy-fmt
on:
  pull_request:

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-test-clippy-fmt
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings
  ENVIRONMENTS:
    - os: ubuntu-latest
      namui_target: x86_64-unknown-linux-gnu
      rust_target: x86_64-unknown-linux-gnu
    - os: ubuntu-latest
      namui_target: wasm32-wasi-web
      rust_target: wasm32-wasip1-threads
    - os: macos-latest
      namui_target: aarch64-apple-darwin
      rust_target: aarch64-apple-darwin
    - os: windows-latest
      namui_target: x86_64-pc-windows-msvc
      rust_target: x86_64-pc-windows-msvc

defaults:
  run:
    shell: bash

jobs:
  test-clippy-fmt:
    strategy:
      matrix:
        include: ${{ env.ENVIROMENTS }}
    runs-on: ${{ matrix.os }}
    outputs:
      diff-artifact-id: ${{ steps.diff-upload.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4

      - name: Fast parallel submodule checkout
        run: |
          git submodule update --init --recursive --jobs 16 --depth 1

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.namui_target == 'x86_64-unknown-linux-gnu'
        with:
          packages: libasound2-dev libfontconfig-dev

      - uses: awalsh128/cache-apt-pkgs-action@latest
        if: matrix.namui_target == 'wasm32-wasi-web'
        with:
          packages: gcc-multilib

      - name: Set up cargo
        run: |
          rustup update
          rustup target add ${{ matrix.rust_target }}

      - name: workspace-maker cache
        uses: actions/cache@v4
        with:
          path: |
            ./github-actions-tools/workspace-maker/target
          key: ${{ matrix.rust_target }}-workspace-maker

      - name: Create workspace Cargo.toml
        run: |
          cargo run --manifest-path github-actions-tools/workspace-maker/Cargo.toml ${{ matrix.namui_target }}

      - name: Workspace cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.namui_target }}

      - run: cargo test
      - run: cargo clippy --target ${{ matrix.rust_target }} --tests --fix
      - run: cargo fmt --all

      - run: git diff > ${{ matrix.namui_target }}.patch

      - name: Upload diff
        id: diff-upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.namui_target }}.patch

  post-test-clippy-fmt:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - test-clippy-fmt
    steps:
      - uses: actions/checkout@v4
        token: ${{ secrets.PAT_CARGO_LOCK_UPDATE }}

      - name: Download diffs
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{ join(needs.test-clippy-fmt.outputs.diff-artifact-id, ',') }}
          path: ${{ runner.temp }}

      - name: Octopus merge changes and push
        run: |
          set -euo pipefail

          echo "=== Collecting patch files ==="
          patches=()
          for patch_file in ${{ runner.temp }}/**/*.patch; do
            if [[ -f "$patch_file" && -s "$patch_file" ]]; then
              target_name=$(basename "$patch_file" .patch)
              patches+=("$target_name:$patch_file")
              echo "Found non-empty patch: $target_name"
            elif [[ -f "$patch_file" ]]; then
              echo "Skipping empty patch: $(basename $patch_file)"
            fi
          done

          if [[ ${#patches[@]} -eq 0 ]]; then
            echo "No patches to apply. Exiting."
            exit 0
          fi

          echo "=== Setting up git config ==="
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          BASE_COMMIT=$(git rev-parse HEAD)
          ORIGINAL_BRANCH=$(git branch --show-current)
          echo "Base commit: $BASE_COMMIT"
          echo "Original branch: $ORIGINAL_BRANCH"

          echo "=== Creating feature branches and applying patches ==="
          branches=()

          for patch_info in "${patches[@]}"; do
            target_name="${patch_info%%:*}"
            patch_file="${patch_info##*:}"
            branch_name="auto-fix/$target_name"
            
            echo "Creating branch $branch_name and applying patch..."
            git checkout -b "$branch_name" "$BASE_COMMIT"
            
            if git apply "$patch_file" 2>/dev/null; then
              git add -A
              git commit -m "Auto-fix: Apply clippy and fmt changes for $target_name"
              branches+=("$branch_name")
              echo "✅ Successfully created $branch_name"
            else
              echo "❌ Failed to apply patch for $target_name"
              echo "Error details:"
              git apply "$patch_file" 2>&1 || true
              echo "::error::Patch $target_name cannot be applied cleanly"
              exit 1
            fi
          done

          git checkout "$ORIGINAL_BRANCH"

          echo "=== Performing octopus merge ==="
          echo "Merging branches: ${branches[*]}"

          if git merge --no-commit --no-ff "${branches[@]}"; then
            git commit -m "Auto-fix: Octopus merge clippy and fmt changes"
            git push origin HEAD
          else
            echo "❌ Octopus merge failed due to conflicts"
            git merge --abort || true
            exit 1
          fi
      - run: |
          echo ${{ join(needs.*.result, ',') }}
          any_test_failed=${{ contains(join(needs.*.result, ','), 'failure') }}
          echo $any_test_failed
          if [[ $any_test_failed == "true" ]]; then
              echo "::error::There are failed job"
              exit 1
          else
              echo "Good. No test failed"
          fi
