[package]
name = "namui"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2024"

[package.metadata.namui]
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "wasm32-wasi-web",
    "aarch64-apple-darwin",
]

[dependencies]
namui-type = { path = "../namui-type" }
namui-hooks = { path = "../namui-hooks" }
namui-cfg = { path = "../namui-cfg" }
namui-particle = { path = "../particle" }
namui-rendering-tree = { path = "../rendering-tree" }
namui-asset-macro = { path = "../asset-macro" }
anyhow = { version = "1.0.77", features = ["backtrace"] }
shader-macro = { path = "../shader-macro" }
futures = "0.3.17"
dashmap = "5"
rand = "0.8.5"
tokio = { path = "../third-party-forks/tokio/tokio", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
    "rt-multi-thread",
    "fs",
] }
orx-parallel = "3.3.0"

[dev-dependencies]
float-cmp = "0.9"
