[package]
name = "namui"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
namui-type = { path = "../namui-type", features = ["namui_internal"] }
namui-hooks = { path = "../namui-hooks" }
lazy_static = "1.4.0"
url = { version = "2", features = ["serde"] }
anyhow = { version = "1.0.77", features = ["backtrace"] }
namui-cfg = { path = "../namui-cfg" }
shader-macro = { path = "../shader-macro" }
hooks-macro = { path = "../hooks-macro" }
serde = { version = "1.0", features = ["derive", "rc"] }
tokio = { version = "1", default-features = false, features = [
    "sync",
    "macros",
] }
serde_json = "1.0"
percent-encoding = "2"
reqwest = "0.11"
futures = "0.3.17"
num = { version = "0.4.0", features = ["std"] }
derivative = "2.2.0"
namui-drawer-sys = { path = "../namui-drawer/sys" }
dashmap = "5"
elsa = { version = "1.10.0", features = ["indexmap"] }
stable_deref_trait = "1.2.0"
bumpalo = { version = "3.15.4", features = ["collections"] }
slab = "0.4.9"
smallvec = "1.13.2"
rustc-hash = "1.1.0"
smol_str = "0.2.1"
indexmap = "2.2.5"
static-tree = { path = "../static-tree" }

[target.'cfg(not(target_family="wasm"))'.dependencies]
tokio = { version = "1", features = ["rt", "fs", "rt-multi-thread"] }
winit = "0.29.4"
rand = "0.8.5"
opener = "0.7.1"
namui-skia = { path = "../skia/skia", features = ["windows", "skia", "winit"] }
ffmpeg-next = { path = "../rust-ffmpeg", features = ["static"] }
crossbeam-channel = "0.5.9"
wasapi = "0.14.0"

[target.'cfg(not(target_family="wasm"))'.dev-dependencies]
wasm-bindgen-test = "0.3.13"
tokio = { version = "1", default-features = false, features = ["rt", "macros"] }
float-cmp = "0.9"


[target.'cfg(target_family="wasm")'.dependencies]
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "HtmlCanvasElement",
    "console",
    "Performance",
    "MouseEvent",
    "KeyboardEvent",
    "WheelEvent",
    "BinaryType",
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Crypto",
    "CssStyleDeclaration",
    "HtmlInputElement",
    "HtmlTextAreaElement",
    "InputEvent",
    "AddEventListenerOptions",
    "FileList",
    "HtmlImageElement",
    "Url",
    "ErrorEvent",
    "HtmlAnchorElement",
    "WritableStream",
    "WritableStreamDefaultWriter",
    "DragEvent",
    "DataTransfer",
    "DataTransferItemList",
    "DataTransferItem",
    "Blob",
    # "AudioContext",
    # "AudioBufferSourceNode",
    # "AudioBuffer",
    # "AudioDestinationNode",
    "HashChangeEvent",
    "ImageBitmap",
] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3.55"
wasm-bindgen-futures = "0.4.28"
once_cell = "1.8.0"
tokio = { version = "1", default-features = false, features = ["sync"] }
dashmap = "4"
bincode = "1.3"
lru = "0.7"
ordered-float = "2.10"
parking_lot = "0.12"
auto_ops = "0.3"
strum = "0.24"
strum_macros = "0.24"
textwrap = "0.15"
unicode-segmentation = "1.9"
serde-wasm-bindgen = "0.5.0"
serde_bytes = "0.11.12"
chumsky = "0.9.2"
namui-skia = { path = "../skia/skia", features = ["wasm-runtime"] }
wasmtimer = "0.2.0"

[target.'cfg(target_family="wasm")'.dev-dependencies]
wasm-bindgen-test = "0.3.13"
tokio = { version = "1", default-features = false, features = [
    "rt",
    "macros",
    "time",
] }
float-cmp = "0.9"
