[package]
name = "namui"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc"]

[dependencies]
namui-type = { path = "../namui-type", features = ["namui_internal"] }
namui-hooks = { path = "../namui-hooks" }
namui-tokio = { path = "../tokio" }
namui-skia = { path = "../skia" }
namui-cfg = { path = "../namui-cfg" }
namui-drawer-sys = { path = "../namui-drawer/sys" }
lazy_static = "1.4.0"
url = { version = "2", features = ["serde"] }
anyhow = { version = "1.0.77", features = ["backtrace"] }
shader-macro = { path = "../shader-macro" }
hooks-macro = { path = "../hooks-macro" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
percent-encoding = "2"
reqwest = "0.11"
futures = "0.3.17"
num = { version = "0.4.0", features = ["std"] }
derivative = "2.2.0"
dashmap = "5"
elsa = { version = "1.10.0", features = ["indexmap"] }
stable_deref_trait = "1.2.0"
bumpalo = { version = "3.15.4", features = ["collections"] }
slab = "0.4.9"
smallvec = "1.13.2"
rustc-hash = "1.1.0"
smol_str = "0.2.1"
indexmap = "2.2.5"
static-tree = { path = "../static-tree" }
rand = "0.8.5"

[target.'cfg(not(target_os="wasi"))'.dependencies]
winit = "0.29.4"
opener = "0.7.1"
ffmpeg-next = { path = "../rust-ffmpeg", features = ["static"] }

[target.'cfg(target_os="windows")'.dependencies]
wasapi = "0.14.0"

[dev-dependencies]
float-cmp = "0.9"
