[package]
name = "namui"
version = "0.1.0"
authors = ["namse <skatpgusskat@naver.com>"]
edition = "2021"

[package.metadata.namui]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[dependencies]
namui-type = { path = "../namui-type" }
namui-hooks = { path = "../namui-hooks" }
namui-skia = { path = "../skia" }
namui-cfg = { path = "../namui-cfg" }
namui-drawer = { path = "../namui-drawer" }
lazy_static = "1.4.0"
url = { version = "2", features = ["serde"] }
anyhow = { version = "1.0.77", features = ["backtrace"] }
shader-macro = { path = "../shader-macro" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
percent-encoding = "2"
futures = "0.3.17"
num = { version = "0.4.0", features = ["std"] }
dashmap = "5"
rand = "0.8.5"
tokio = { path = "../third-party-forks/tokio/tokio", features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time",
    "rt-multi-thread",
    "fs",
] }
reqwest = { path = "../third-party-forks/reqwest" }
rusqlite = { path = "../third-party-forks/rusqlite", features = ["bundled"] }

[target.'cfg(not(target_os="wasi"))'.dependencies]
winit = "0.29.4"
opener = "0.7.1"

[target.'cfg(target_os="windows")'.dependencies]
wasapi = "0.14.0"
ffmpeg-next = { path = "../rust-ffmpeg", features = ["static"] }

[dev-dependencies]
float-cmp = "0.9"
